-- GENERATED by scripts/cmd/generate-colors — DO NOT EDIT
-- Ghost Visor カラーパレット共有モジュール
-- TOMLソース: colors/ghost-visor.toml
-- 単一ソース原則: このモジュールから全プラグイン設定が色を参照する

local M = {}

M.colors = {
  -- コアカラー
  bg = "#1A2340",           -- Main (Pure Black) [core.background]
  darkest_bg = "#0C1226",   -- Deepest Shadow [core.darkest_bg]
  panel_bg = "#332E56",     -- Dark Teal Panel [core.panel_bg]
  dark_shadow = "#1F2745",  -- UI Shadow [core.ui_shadow]
  border = "#4C4C74",       -- UI Border [teals.border]
  mid_gray = "#453C5F",     -- Background fill / intentional dim only [blues_slates.slate_mid]
  subdued_fg = "#9E97B8",   -- Subdued foreground [foregrounds.subdued]
  light_gray = "#ABA4C4",   -- Dim text [foregrounds.dim]

  -- Visibility improvements
  punctuation_gray = "#AEACC4",  -- 句読点 [blues_slates.punctuation_gray]
  comment_gray = "#A5A2BC",      -- コメント [blues_slates.comment_gray]
  git_blame_gray = "#A8A5C2",    -- Git blame [blues_slates.git_blame_gray]
  operator = "#92BFD9",     -- Clear Teal [teals.mid_bright]
  fg = "#CDE9F5",           -- Main Text [foregrounds.main]
  foreground_bright = "#96D7F5",   -- Bright foreground [foregrounds.bright]
  highlight_white = "#F8FCFD", -- Purest [ansi.bright_white]

  -- アクセントカラー
  teal_bright = "#58CAF8",         -- Bright Teal [teals.bright]
  foreground_heading = "#B79AD0",  -- Heading foreground [foregrounds.heading]
  cloud_slate = "#BEB8D8", -- Cloud Slate [blues_slates.cloud_slate]

  -- 拡張セマンティック
  purple_accent = "#B79AD0", -- Muted Purple (Keyword) [purples.muted_purple]
  syntax_violet = "#C69BF6", -- Syntax Violet [semantic.keyword]
  syntax_function = "#58CAF8", -- Syntax function [semantic.function]
  syntax_type = "#AFB8D9", -- Syntax type [semantic.type]
  syntax_number = "#96D7F5", -- Syntax number [semantic.number]
  syntax_constant = "#D0D4F0", -- Syntax constant [semantic.constant]
  syntax_variable = "#CDE9F5", -- Syntax variable [semantic.variable]
  syntax_builtin_variable = "#88CBEA", -- Syntax builtin variable [semantic.builtin_variable]
  success = "#76D6C4",       -- Success indicator [semantic.success]
  diagnostic_error = "#E2839A", -- Diagnostic error [semantic.error]
  diagnostic_warn = "#BEB8D8", -- Diagnostic warning [semantic.warning]
  diagnostic_info = "#8AB8DE", -- Diagnostic info [semantic.info]
  diagnostic_hint = "#58CAF8", -- Diagnostic hint [semantic.hint]
  git_added = "#76D6C4",         -- Git added [git.added]
  git_changed = "#CE7BD2",     -- Git changed [git.changed]
  git_deleted = "#ABA4C4",     -- Git deleted [git.deleted]
  ui_target_bg = "#D0D4F0",   -- UI target background [ui.target_bg]
  ui_accent_fg = "#D0D4F0",   -- UI ambient accent [ui.accent_fg]
  ocean_blue = "#3C5684",    -- Ocean Blue [blues_slates.ocean_blue]
  lavender = "#D0D4F0",      -- Lavender (Constant) [purples.lavender]

  -- ANSI/Terminal
  ansi_black = "#0C1226", -- ANSI Black [ansi.black]
  ansi_red = "#C97F9E", -- ANSI Red [ansi.red]
  ansi_green = "#2FA5A0", -- ANSI Green [ansi.green]
  ansi_yellow = "#CAB083", -- ANSI Yellow [ansi.yellow]
  ansi_blue = "#7089D6", -- ANSI Blue [ansi.blue]
  ansi_magenta = "#C86FBE", -- ANSI Magenta [ansi.magenta]
  ansi_cyan = "#58CAF8", -- ANSI Cyan [ansi.cyan]
  ansi_white = "#CDE9F5", -- ANSI White [ansi.white]
  ansi_bright_black = "#565273", -- ANSI Bright Black [ansi.bright_black]
  ansi_bright_red = "#E2839A", -- ANSI Bright Red [ansi.bright_red]
  ansi_bright_green = "#76D6C4", -- ANSI Bright Green [ansi.bright_green]
  ansi_bright_yellow = "#DFBE90", -- ANSI Bright Yellow [ansi.bright_yellow]
  ansi_bright_blue = "#AFB8D9", -- ANSI Bright Blue [ansi.bright_blue]
  ansi_bright_magenta = "#E6BCF4", -- ANSI Bright Magenta [ansi.bright_magenta]
  ansi_bright_cyan = "#96D7F5", -- ANSI Bright Cyan [ansi.bright_cyan]
  ansi_bright_white = "#F8FCFD", -- ANSI Bright White [ansi.bright_white]

  -- その他
  sky_slate = "#AFB8D9",        -- Sky Slate (Icon) [blues_slates.sky_slate]
  selection = "#9385C8",    -- Clear Teal [core.selection_bg]
  selection_fg = "#0C1226", -- Background for contrast
  string = "#9ABED3",       -- Base Teal [semantic.string]

  -- Diff背景カラー
  diff_add_bg = "#1A3D48",      -- Diff Add背景 [nvim.diff_add_bg]
  diff_change_bg = "#332A5E",   -- Diff Change背景 [nvim.diff_change_bg]
  diff_delete_bg = "#421F32",   -- Diff Delete背景 [nvim.diff_delete_bg]
  diff_add_inline_bg = "#2E6472",     -- Word-diff add背景 [nvim.diff_add_inline_bg]
  diff_change_inline_bg = "#52458F",  -- Word-diff change背景 [nvim.diff_change_inline_bg]
  diff_delete_inline_bg = "#71364A",  -- Word-diff delete背景 [nvim.diff_delete_inline_bg]
}

return M
