-- GENERATED by scripts/cmd/generate-colors — DO NOT EDIT
-- Ghost Visor カラーパレット共有モジュール
-- TOMLソース: colors/ghost-visor.toml
-- 単一ソース原則: このモジュールから全プラグイン設定が色を参照する

local M = {}

M.colors = {
  -- コアカラー
  bg = "#202A42",           -- Main (Pure Black) [core.background]
  darkest_bg = "#141B2D",   -- Deepest Shadow [core.darkest_bg]
  panel_bg = "#324664",     -- Dark Teal Panel [core.panel_bg]
  dark_shadow = "#242F48",  -- UI Shadow [core.ui_shadow]
  gutter_bg = "#1A2235",    -- Gutter background [nvim.gutter_bg]
  border = "#45799D",       -- UI Border [teals.border]
  mid_gray = "#4A4953",     -- Background fill / intentional dim only [blues_slates.slate_mid]
  subdued_fg = "#949DB0",   -- Subdued foreground [foregrounds.subdued]
  light_gray = "#ADBAC9",   -- Dim text [foregrounds.dim]

  -- Visibility improvements
  punctuation_gray = "#B3B9C7",  -- 句読点 [blues_slates.punctuation_gray]
  comment_gray = "#B1B9CA",      -- コメント [blues_slates.comment_gray]
  git_blame_gray = "#B1B9CD",    -- Git blame [blues_slates.git_blame_gray]
  operator = "#92BFD9",     -- Clear Teal [teals.mid_bright]
  fg = "#CDE9F5",           -- Main Text [foregrounds.main]
  near_white = "#9FDBF7",   -- Brightest [foregrounds.bright]
  highlight_white = "#F8FCFD", -- Purest [ansi.bright_white]

  -- アクセントカラー
  cyan = "#58CAF8",         -- Vibrant Teal [teals.bright]
  bright_cyan = "#88CBEA",  -- Heading Cyan [foregrounds.heading]
  magenta = "#CEADE1",      -- Glitch Purple (error accent) [semantic.error]
  bright_magenta = "#B8BCD8", -- Cloud Slate [blues_slates.cloud_slate]

  -- 拡張セマンティック
  purple_accent = "#B4B6DA", -- Muted Purple (Keyword) [purples.muted_purple]
  syntax_violet = "#BFADFF", -- Syntax Violet [semantic.keyword]
  success = "#62C9C2",       -- Success indicator [semantic.success]
  diagnostic_error = "#CEADE1", -- Diagnostic error [semantic.error]
  diagnostic_warn = "#B8BCD8", -- Diagnostic warning [semantic.warning]
  diagnostic_info = "#88CBEA", -- Diagnostic info [semantic.info]
  diagnostic_hint = "#58CAF8", -- Diagnostic hint [semantic.hint]
  git_added = "#62C9C2",         -- Git added [git.added]
  git_changed = "#CEADE1",     -- Git changed [git.changed]
  git_deleted = "#ADBAC9",     -- Git deleted [git.deleted]
  ui_target_bg = "#CEADE1",   -- UI target background [ui.target_bg]
  ui_accent_fg = "#CEADE1",   -- UI ambient accent [ui.accent_fg]
  ocean_blue = "#375F98",    -- Ocean Blue [blues_slates.ocean_blue]
  lavender = "#D0D4F0",      -- Lavender (Constant) [purples.lavender]

  -- ANSI/Terminal
  ansi_black = "#141B2D", -- ANSI Black [ansi.black]
  ansi_red = "#C67F9E", -- ANSI Red [ansi.red]
  ansi_green = "#2FA5A0", -- ANSI Green [ansi.green]
  ansi_yellow = "#C2B08D", -- ANSI Yellow [ansi.yellow]
  ansi_blue = "#6393D7", -- ANSI Blue [ansi.blue]
  ansi_magenta = "#D96DC0", -- ANSI Magenta [ansi.magenta]
  ansi_cyan = "#58CAF8", -- ANSI Cyan [ansi.cyan]
  ansi_white = "#CDE9F5", -- ANSI White [ansi.white]
  ansi_bright_black = "#5E5A63", -- ANSI Bright Black [ansi.bright_black]
  ansi_bright_red = "#D38AA6", -- ANSI Bright Red [ansi.bright_red]
  ansi_bright_green = "#52C4BC", -- ANSI Bright Green [ansi.bright_green]
  ansi_bright_yellow = "#DFBE90", -- ANSI Bright Yellow [ansi.bright_yellow]
  ansi_bright_blue = "#A8B2D6", -- ANSI Bright Blue [ansi.bright_blue]
  ansi_bright_magenta = "#EBC1F8", -- ANSI Bright Magenta [ansi.bright_magenta]
  ansi_bright_cyan = "#9FDBF7", -- ANSI Bright Cyan [ansi.bright_cyan]
  ansi_bright_white = "#F8FCFD", -- ANSI Bright White [ansi.bright_white]

  -- その他
  white = "#AFB8D9",        -- Sky Slate (Icon) [blues_slates.sky_slate]
  selection = "#5199C2",    -- Clear Teal [core.selection_bg]
  selection_fg = "#141B2D", -- Background for contrast
  string = "#9ABED3",       -- Base Teal [semantic.string]

  -- Diff背景カラー
  diff_add_bg = "#1E3A44",      -- Diff Add背景 [nvim.diff_add_bg]
  diff_change_bg = "#2B2650",   -- Diff Change背景 [nvim.diff_change_bg]
  diff_delete_bg = "#302230",   -- Diff Delete背景 [nvim.diff_delete_bg]
  diff_add_inline_bg = "#2E5D6B",     -- Word-diff add背景 [nvim.diff_add_inline_bg]
  diff_change_inline_bg = "#4C3C78",  -- Word-diff change背景 [nvim.diff_change_inline_bg]
  diff_delete_inline_bg = "#5E3245",  -- Word-diff delete背景 [nvim.diff_delete_inline_bg]
}

return M
