package main

import (
	"bytes"
	"errors"
	"flag"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"

	"github.com/sunagawasei/dotfiles/scripts/internal/colorutil"
	"github.com/sunagawasei/dotfiles/scripts/internal/palette"
	"github.com/sunagawasei/dotfiles/scripts/internal/xterm"
)

const generatedNotice = "GENERATED by scripts/cmd/generate-colors — DO NOT EDIT"

type colorPalette struct {
	Metadata    map[string]string `toml:"metadata"`
	Core        map[string]string `toml:"core"`
	Foregrounds map[string]string `toml:"foregrounds"`
	Teals       map[string]string `toml:"teals"`
	BluesSlates map[string]string `toml:"blues_slates"`
	Purples     map[string]string `toml:"purples"`
	Semantic    map[string]string `toml:"semantic"`
	ANSI        map[string]string `toml:"ansi"`
	WezTerm     map[string]string `toml:"wezterm"`
	Nvim        map[string]string `toml:"nvim"`
	Zsh         map[string]string `toml:"zsh"`
}

type outputFile struct {
	path    string
	content string
}

type markerOutput struct {
	path  string
	begin string
	end   string
	block string
}

var placeholderPattern = regexp.MustCompile(`\{\{(?:(lower|xterm|rgb):)?([a-z_]+)\.([a-z_]+)\}\}`)

func main() {
	check := flag.Bool("check", false, "check whether generated files are up to date")
	flag.Usage = func() {
		fmt.Fprintf(flag.CommandLine.Output(), "Usage: %s [--check] [palette.toml]\n", os.Args[0])
		flag.PrintDefaults()
	}
	flag.Parse()

	if flag.NArg() > 1 {
		flag.Usage()
		os.Exit(2)
	}

	root, err := palette.FindRepositoryRoot()
	if err != nil {
		exitError(err)
	}

	palettePath, err := palette.ResolvePath(root, flag.Args())
	if err != nil {
		exitError(err)
	}

	palette, err := loadColorPalette(palettePath)
	if err != nil {
		exitError(err)
	}

	files, markers, err := generateOutputs(root, filepath.Base(palettePath), palette)
	if err != nil {
		exitError(err)
	}

	changed, err := applyOutputs(files, markers, *check)
	if err != nil {
		exitError(err)
	}
	if *check && changed {
		fmt.Fprintln(os.Stderr, "generated color files are out of date")
		os.Exit(1)
	}

	if *check {
		fmt.Println("All generated color files are up to date.")
	} else if changed {
		fmt.Printf("Generated color files from %s.\n", filepath.ToSlash(relativePath(root, palettePath)))
	} else {
		fmt.Println("Generated color files are already up to date.")
	}
}

func exitError(err error) {
	fmt.Fprintf(os.Stderr, "generate-colors: %v\n", err)
	os.Exit(1)
}

func loadColorPalette(path string) (*colorPalette, error) {
	loaded, err := palette.Load[colorPalette](path)
	if err != nil {
		var loadErr *palette.LoadError
		if errors.As(err, &loadErr) {
			switch loadErr.Stage {
			case palette.LoadStageRead:
				return nil, fmt.Errorf("read palette: %w", loadErr.Err)
			case palette.LoadStageParse:
				return nil, fmt.Errorf("parse palette: %w", loadErr.Err)
			}
		}
		return nil, err
	}
	if loaded.Metadata["name"] == "" {
		return nil, errors.New("palette metadata.name is required")
	}
	return loaded, nil
}

func (p *colorPalette) section(name string) (map[string]string, error) {
	switch name {
	case "metadata":
		return p.Metadata, nil
	case "core":
		return p.Core, nil
	case "foregrounds":
		return p.Foregrounds, nil
	case "teals":
		return p.Teals, nil
	case "blues_slates":
		return p.BluesSlates, nil
	case "purples":
		return p.Purples, nil
	case "semantic":
		return p.Semantic, nil
	case "ansi":
		return p.ANSI, nil
	case "wezterm":
		return p.WezTerm, nil
	case "nvim":
		return p.Nvim, nil
	case "zsh":
		return p.Zsh, nil
	default:
		return nil, fmt.Errorf("unknown palette section %q", name)
	}
}

func (p *colorPalette) value(sectionName, key string) (string, error) {
	section, err := p.section(sectionName)
	if err != nil {
		return "", err
	}
	value, ok := section[key]
	if !ok || value == "" {
		return "", fmt.Errorf("missing palette value %s.%s", sectionName, key)
	}
	if sectionName != "metadata" {
		if _, _, _, err := colorutil.ParseHexRGB8(value); err != nil {
			return "", fmt.Errorf("invalid palette value %s.%s: %w", sectionName, key, err)
		}
	}
	return value, nil
}

func renderTemplate(template string, palette *colorPalette) (string, error) {
	var renderErr error
	rendered := placeholderPattern.ReplaceAllStringFunc(template, func(placeholder string) string {
		if renderErr != nil {
			return placeholder
		}
		parts := placeholderPattern.FindStringSubmatch(placeholder)
		value, err := palette.value(parts[2], parts[3])
		if err != nil {
			renderErr = err
			return placeholder
		}
		switch parts[1] {
		case "lower":
			return strings.ToLower(value)
		case "xterm":
			index, _, err := xterm.Nearest256(value)
			if err != nil {
				renderErr = err
				return placeholder
			}
			return strconv.Itoa(index)
		case "rgb":
			r, g, b, err := colorutil.ParseHexRGB8(value)
			if err != nil {
				renderErr = err
				return placeholder
			}
			return fmt.Sprintf("%d;%d;%d", r, g, b)
		default:
			return value
		}
	})
	if renderErr != nil {
		return "", renderErr
	}
	return rendered, nil
}

func generateOutputs(root, sourceName string, palette *colorPalette) ([]outputFile, []markerOutput, error) {
	templates := []struct {
		path     string
		template string
	}{
		{filepath.Join(root, "nvim/lua/config/palette.lua"), paletteLuaTemplate},
		{filepath.Join(root, "wezterm/colors.lua"), weztermLuaTemplate},
		{filepath.Join(root, "home-manager/colors.nix"), nixColorsTemplate},
		{filepath.Join(root, "claude/themes/ghost-visor.json"), claudeThemeTemplate},
		{filepath.Join(root, "bat/themes/ghost-visor.tmTheme"), batThemeTemplate},
	}

	files := make([]outputFile, 0, len(templates))
	for _, item := range templates {
		template := strings.ReplaceAll(item.template, "{{source}}", sourceName)
		content, err := renderTemplate(template, palette)
		if err != nil {
			return nil, nil, fmt.Errorf("render %s: %w", relativePath(root, item.path), err)
		}
		files = append(files, outputFile{path: item.path, content: content})
	}

	markerTemplates := []struct {
		path     string
		begin    string
		end      string
		template string
	}{
		{
			path: filepath.Join(root, "lazygit/config.yml"), begin: "    # BEGIN GENERATED COLORS", end: "    # END GENERATED COLORS",
			template: lazygitTemplate,
		},
		{
			path: filepath.Join(root, "gh-dash/config.yml"), begin: "        # BEGIN GENERATED COLORS", end: "        # END GENERATED COLORS",
			template: ghDashTemplate,
		},
		{
			path: filepath.Join(root, "herdr/config.toml"), begin: "# BEGIN GENERATED COLORS", end: "# END GENERATED COLORS",
			template: herdrTemplate,
		},
		{
			path: filepath.Join(root, "vim/vimrc"), begin: `" BEGIN GENERATED COLORS`, end: `" END GENERATED COLORS`,
			template: vimTemplate,
		},
		{
			path: filepath.Join(root, "claude/statusline.sh"), begin: "# BEGIN GENERATED COLORS: ANSI", end: "# END GENERATED COLORS: ANSI",
			template: statuslineANSITemplate,
		},
		{
			path: filepath.Join(root, "claude/statusline.sh"), begin: "# BEGIN GENERATED COLORS: SEGMENTS", end: "# END GENERATED COLORS: SEGMENTS",
			template: statuslineSegmentsTemplate,
		},
		{
			path: filepath.Join(root, "COLOR-SYSTEM.md"), begin: "<!-- BEGIN GENERATED COLORS -->", end: "<!-- END GENERATED COLORS -->",
			template: colorSystemANSITemplate,
		},
	}

	markers := make([]markerOutput, 0, len(markerTemplates))
	for _, item := range markerTemplates {
		block, err := renderTemplate(item.template, palette)
		if err != nil {
			return nil, nil, fmt.Errorf("render marker block for %s: %w", relativePath(root, item.path), err)
		}
		markers = append(markers, markerOutput{path: item.path, begin: item.begin, end: item.end, block: block})
	}
	return files, markers, nil
}

func applyOutputs(files []outputFile, markers []markerOutput, check bool) (bool, error) {
	expected := make(map[string]string, len(files)+len(markers))
	for _, file := range files {
		expected[file.path] = file.content
	}

	for _, marker := range markers {
		content, ok := expected[marker.path]
		if !ok {
			data, err := os.ReadFile(marker.path)
			if err != nil {
				return false, fmt.Errorf("read %s: %w", marker.path, err)
			}
			content = string(data)
		}
		updated, err := replaceGeneratedBlock(content, marker)
		if err != nil {
			return false, err
		}
		expected[marker.path] = updated
	}

	paths := make([]string, 0, len(expected))
	for path := range expected {
		paths = append(paths, path)
	}
	sort.Strings(paths)

	changed := false
	for _, path := range paths {
		actual, err := os.ReadFile(path)
		if err != nil && !os.IsNotExist(err) {
			return false, fmt.Errorf("read %s: %w", path, err)
		}
		want := []byte(expected[path])
		if bytes.Equal(actual, want) {
			continue
		}
		changed = true
		if check {
			if err := printUnifiedDiff(path, actual, want); err != nil {
				return false, err
			}
			continue
		}
		if err := writePreservingMode(path, want); err != nil {
			return false, err
		}
		fmt.Printf("updated %s\n", path)
	}
	return changed, nil
}

func replaceGeneratedBlock(content string, marker markerOutput) (string, error) {
	beginIndex := strings.Index(content, marker.begin)
	if beginIndex >= 0 {
		endRelative := strings.Index(content[beginIndex:], marker.end)
		if endRelative < 0 {
			return "", fmt.Errorf("missing end marker %q in %s", marker.end, marker.path)
		}
		endIndex := beginIndex + endRelative + len(marker.end)
		for endIndex < len(content) && content[endIndex] == '\n' {
			endIndex++
		}
		return content[:beginIndex] + marker.block + content[endIndex:], nil
	}

	return "", fmt.Errorf("missing start marker %q in %s", marker.begin, marker.path)
}

func writePreservingMode(path string, content []byte) error {
	mode := os.FileMode(0o644)
	if info, err := os.Stat(path); err == nil {
		mode = info.Mode().Perm()
	} else if !os.IsNotExist(err) {
		return fmt.Errorf("stat %s: %w", path, err)
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("create parent directory for %s: %w", path, err)
	}
	if err := os.WriteFile(path, content, mode); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	return nil
}

func printUnifiedDiff(path string, actual, expected []byte) error {
	actualFile, err := os.CreateTemp("", "generate-colors-actual-*")
	if err != nil {
		return fmt.Errorf("create diff input: %w", err)
	}
	defer os.Remove(actualFile.Name())
	if _, err := actualFile.Write(actual); err != nil {
		actualFile.Close()
		return fmt.Errorf("write diff input: %w", err)
	}
	if err := actualFile.Close(); err != nil {
		return fmt.Errorf("close diff input: %w", err)
	}

	expectedFile, err := os.CreateTemp("", "generate-colors-expected-*")
	if err != nil {
		return fmt.Errorf("create diff input: %w", err)
	}
	defer os.Remove(expectedFile.Name())
	if _, err := expectedFile.Write(expected); err != nil {
		expectedFile.Close()
		return fmt.Errorf("write diff input: %w", err)
	}
	if err := expectedFile.Close(); err != nil {
		return fmt.Errorf("close diff input: %w", err)
	}

	cmd := exec.Command("diff", "-u", "--label", path, "--label", path+" (generated)", actualFile.Name(), expectedFile.Name())
	output, err := cmd.CombinedOutput()
	if len(output) > 0 {
		fmt.Fprint(os.Stderr, string(output))
	}
	var exitErr *exec.ExitError
	if err != nil && (!errors.As(err, &exitErr) || exitErr.ExitCode() != 1) {
		return fmt.Errorf("diff %s: %w", path, err)
	}
	return nil
}

func relativePath(root, path string) string {
	relative, err := filepath.Rel(root, path)
	if err != nil {
		return path
	}
	return relative
}

// claudeThemeTemplate derives the Claude Code theme from existing ghost-visor.toml keys.
// Changes to shared keys such as ansi.*, nvim.*, and core.* must flow through to this theme.
// name and base remain literals because they are Claude Code-specific values.
const claudeThemeTemplate = `{
  "name": "Ghost Visor",
  "base": "dark-ansi",
  "overrides": {
    "claude": "{{teals.bright}}",
    "claudeShimmer": "{{foregrounds.bright}}",
    "claudeBlue_FOR_SYSTEM_SPINNER": "{{teals.bright}}",
    "claudeBlueShimmer_FOR_SYSTEM_SPINNER": "{{foregrounds.bright}}",
    "text": "{{foregrounds.main}}",
    "inverseText": "{{core.darkest_bg}}",
    "inactive": "{{foregrounds.dim}}",
    "inactiveShimmer": "{{blues_slates.cloud_slate}}",
    "subtle": "{{foregrounds.subdued}}",
    "suggestion": "{{teals.mid_bright}}",
    "permission": "{{teals.border}}",
    "permissionShimmer": "{{teals.bright}}",
    "remember": "{{purples.bright_purple}}",
    "skill": "{{purples.bright_purple}}",
    "effortUltra": "{{purples.bright_purple}}",
    "chromeYellow": "{{ansi.bright_yellow}}",
    "professionalBlue": "{{ansi.blue}}",
    "success": "{{semantic.success}}",
    "error": "{{ansi.magenta}}",
    "warning": "{{ansi.yellow}}",
    "warningShimmer": "{{ansi.bright_yellow}}",
    "merged": "{{purples.bright_purple}}",
    "promptBorder": "{{teals.border}}",
    "promptBorderShimmer": "{{teals.bright}}",
    "planMode": "{{teals.bright}}",
    "autoAccept": "{{semantic.success}}",
    "autoAcceptShimmer": "{{foregrounds.bright}}",
    "bashBorder": "{{ansi.magenta}}",
    "ide": "{{teals.bright}}",
    "fastMode": "{{ansi.bright_magenta}}",
    "fastModeShimmer": "{{ansi.bright_white}}",
    "diffAdded": "{{nvim.diff_add_bg}}",
    "diffRemoved": "{{nvim.diff_delete_bg}}",
    "diffAddedDimmed": "{{nvim.gutter_bg}}",
    "diffRemovedDimmed": "{{core.ui_shadow}}",
    "diffAddedWord": "{{nvim.diff_add_inline_bg}}",
    "diffRemovedWord": "{{nvim.diff_delete_inline_bg}}",
    "userMessageBackground": "{{core.ui_shadow}}",
    "userMessageBackgroundHover": "{{core.active_line}}",
    "bashMessageBackgroundColor": "{{purples.dark_rose}}",
    "memoryBackgroundColor": "{{nvim.diff_change_bg}}",
    "selectionBg": "{{blues_slates.slate_dark}}",
    "rate_limit_fill": "{{teals.bright}}",
    "rate_limit_empty": "{{core.ui_shadow}}",
    "briefLabelYou": "{{foregrounds.dim}}",
    "briefLabelClaude": "{{teals.bright}}"
  }
}
`

const paletteLuaTemplate = `-- ` + generatedNotice + `
-- {{metadata.name}} カラーパレット共有モジュール
-- TOMLソース: colors/{{source}}
-- 単一ソース原則: このモジュールから全プラグイン設定が色を参照する

local M = {}

M.colors = {
  -- コアカラー
  bg = "{{core.background}}",           -- Main (Pure Black) [core.background]
  darkest_bg = "{{core.darkest_bg}}",   -- Deepest Shadow [core.darkest_bg]
  panel_bg = "{{core.panel_bg}}",     -- Dark Teal Panel [core.panel_bg]
  dark_shadow = "{{core.ui_shadow}}",  -- UI Shadow [core.ui_shadow]
  gutter_bg = "{{nvim.gutter_bg}}",    -- Gutter background [nvim.gutter_bg]
  border = "{{teals.border}}",       -- UI Border [teals.border]
  mid_gray = "{{blues_slates.slate_mid}}",     -- Background fill / intentional dim only [blues_slates.slate_mid]
  subdued_fg = "{{foregrounds.subdued}}",   -- Subdued foreground [foregrounds.subdued]
  light_gray = "{{foregrounds.dim}}",   -- Dim text [foregrounds.dim]

  -- Visibility improvements
  punctuation_gray = "{{blues_slates.punctuation_gray}}",  -- 句読点 [blues_slates.punctuation_gray]
  comment_gray = "{{blues_slates.comment_gray}}",      -- コメント [blues_slates.comment_gray]
  git_blame_gray = "{{blues_slates.git_blame_gray}}",    -- Git blame [blues_slates.git_blame_gray]
  operator = "{{teals.mid_bright}}",     -- Clear Teal [teals.mid_bright]
  fg = "{{foregrounds.main}}",           -- Main Text [foregrounds.main]
  near_white = "{{foregrounds.bright}}",   -- Brightest [foregrounds.bright]
  highlight_white = "{{ansi.bright_white}}", -- Purest [ansi.bright_white]

  -- アクセントカラー
  cyan = "{{teals.bright}}",         -- Vibrant Teal [teals.bright]
  bright_cyan = "{{foregrounds.heading}}",  -- Heading Cyan [foregrounds.heading]
  magenta = "{{zsh.error}}",      -- Glitch Purple (error accent)
  bright_magenta = "{{blues_slates.cloud_slate}}", -- Cloud Slate [blues_slates.cloud_slate]

  -- 拡張セマンティック
  purple_accent = "{{purples.muted_purple}}", -- Muted Purple (Keyword) [purples.muted_purple]
  syntax_violet = "{{semantic.keyword}}", -- Syntax Violet [semantic.keyword]
  success = "{{semantic.success}}",       -- Success indicator [semantic.success]
  ocean_blue = "{{blues_slates.ocean_blue}}",    -- Ocean Blue [blues_slates.ocean_blue]
  lavender = "{{purples.lavender}}",      -- Lavender (Constant) [purples.lavender]

  -- ANSI/Terminal
  ansi_black = "{{ansi.black}}", -- ANSI Black [ansi.black]
  ansi_red = "{{ansi.red}}", -- ANSI Red [ansi.red]
  ansi_green = "{{ansi.green}}", -- ANSI Green [ansi.green]
  ansi_yellow = "{{ansi.yellow}}", -- ANSI Yellow [ansi.yellow]
  ansi_blue = "{{ansi.blue}}", -- ANSI Blue [ansi.blue]
  ansi_magenta = "{{ansi.magenta}}", -- ANSI Magenta [ansi.magenta]
  ansi_cyan = "{{ansi.cyan}}", -- ANSI Cyan [ansi.cyan]
  ansi_white = "{{ansi.white}}", -- ANSI White [ansi.white]
  ansi_bright_black = "{{ansi.bright_black}}", -- ANSI Bright Black [ansi.bright_black]
  ansi_bright_red = "{{ansi.bright_red}}", -- ANSI Bright Red [ansi.bright_red]
  ansi_bright_green = "{{ansi.bright_green}}", -- ANSI Bright Green [ansi.bright_green]
  ansi_bright_yellow = "{{ansi.bright_yellow}}", -- ANSI Bright Yellow [ansi.bright_yellow]
  ansi_bright_blue = "{{ansi.bright_blue}}", -- ANSI Bright Blue [ansi.bright_blue]
  ansi_bright_magenta = "{{ansi.bright_magenta}}", -- ANSI Bright Magenta [ansi.bright_magenta]
  ansi_bright_cyan = "{{ansi.bright_cyan}}", -- ANSI Bright Cyan [ansi.bright_cyan]
  ansi_bright_white = "{{ansi.bright_white}}", -- ANSI Bright White [ansi.bright_white]

  -- その他
  white = "{{blues_slates.sky_slate}}",        -- Sky Slate (Icon) [blues_slates.sky_slate]
  selection = "{{core.selection_bg}}",    -- Clear Teal [core.selection_bg]
  selection_fg = "{{core.selection_fg}}", -- Background for contrast
  string = "{{semantic.string}}",       -- Base Teal [semantic.string]

  -- Diff背景カラー
  diff_add_bg = "{{nvim.diff_add_bg}}",      -- Diff Add背景 [nvim.diff_add_bg]
  diff_change_bg = "{{nvim.diff_change_bg}}",   -- Diff Change背景 [nvim.diff_change_bg]
  diff_delete_bg = "{{nvim.diff_delete_bg}}",   -- Diff Delete背景 [nvim.diff_delete_bg]
  diff_add_inline_bg = "{{nvim.diff_add_inline_bg}}",     -- Word-diff add背景 [nvim.diff_add_inline_bg]
  diff_change_inline_bg = "{{nvim.diff_change_inline_bg}}",  -- Word-diff change背景 [nvim.diff_change_inline_bg]
  diff_delete_inline_bg = "{{nvim.diff_delete_inline_bg}}",  -- Word-diff delete背景 [nvim.diff_delete_inline_bg]
}

return M
`

const weztermLuaTemplate = `-- ` + generatedNotice + `
-- TOML source: colors/{{source}}

return {
  metadata = { name = "{{metadata.name}}" },
  core = {
    background = "{{core.background}}",
    darkest_bg = "{{core.darkest_bg}}",
    panel_bg = "{{core.panel_bg}}",
    ui_shadow = "{{core.ui_shadow}}",
    active_line = "{{core.active_line}}",
    selection_bg = "{{core.selection_bg}}",
    selection_fg = "{{core.selection_fg}}",
  },
  foregrounds = {
    main = "{{foregrounds.main}}",
    bright = "{{foregrounds.bright}}",
    dim = "{{foregrounds.dim}}",
    subdued = "{{foregrounds.subdued}}",
    heading = "{{foregrounds.heading}}",
  },
  teals = {
    bright = "{{teals.bright}}",
    mid_bright = "{{teals.mid_bright}}",
    standard = "{{teals.standard}}",
    muted = "{{teals.muted}}",
    deep = "{{teals.deep}}",
    border = "{{teals.border}}",
    dark_accent = "{{teals.dark_accent}}",
    sea_green = "{{teals.sea_green}}",
  },
  blues_slates = {
    slate_mid = "{{blues_slates.slate_mid}}",
    punctuation_gray = "{{blues_slates.punctuation_gray}}",
    comment_gray = "{{blues_slates.comment_gray}}",
    git_blame_gray = "{{blues_slates.git_blame_gray}}",
    slate_dark = "{{blues_slates.slate_dark}}",
    ocean_blue = "{{blues_slates.ocean_blue}}",
    sky_slate = "{{blues_slates.sky_slate}}",
    cloud_slate = "{{blues_slates.cloud_slate}}",
    deep_ocean = "{{blues_slates.deep_ocean}}",
  },
  purples = {
    lavender = "{{purples.lavender}}",
    muted_purple = "{{purples.muted_purple}}",
    bright_purple = "{{purples.bright_purple}}",
    dark_purple = "{{purples.dark_purple}}",
    deep_glitch = "{{purples.deep_glitch}}",
    soft_magenta = "{{purples.soft_magenta}}",
    dark_rose = "{{purples.dark_rose}}",
  },
  semantic = {
    success = "{{semantic.success}}",
    warning = "{{semantic.warning}}",
    error = "{{semantic.error}}",
    info = "{{semantic.info}}",
    comment = "{{semantic.comment}}",
    git_blame = "{{semantic.git_blame}}",
    string = "{{semantic.string}}",
    keyword = "{{semantic.keyword}}",
    punctuation = "{{semantic.punctuation}}",
    function_color = "{{semantic.function}}",
    type_color = "{{semantic.type}}",
    variable = "{{semantic.variable}}",
    number = "{{semantic.number}}",
    operator = "{{semantic.operator}}",
    constant = "{{semantic.constant}}",
  },
  ansi = {
    black = "{{ansi.black}}",
    red = "{{ansi.red}}",
    green = "{{ansi.green}}",
    yellow = "{{ansi.yellow}}",
    blue = "{{ansi.blue}}",
    magenta = "{{ansi.magenta}}",
    cyan = "{{ansi.cyan}}",
    white = "{{ansi.white}}",
    bright_black = "{{ansi.bright_black}}",
    bright_red = "{{ansi.bright_red}}",
    bright_green = "{{ansi.bright_green}}",
    bright_yellow = "{{ansi.bright_yellow}}",
    bright_blue = "{{ansi.bright_blue}}",
    bright_magenta = "{{ansi.bright_magenta}}",
    bright_cyan = "{{ansi.bright_cyan}}",
    bright_white = "{{ansi.bright_white}}",
  },
  wezterm = {
    background = "{{wezterm.background}}",
    tab_bar = "{{wezterm.tab_bar}}",
    active_tab = "{{wezterm.active_tab}}",
    inactive_tab = "{{wezterm.inactive_tab}}",
    active_tab_fg = "{{wezterm.active_tab_fg}}",
    inactive_tab_fg = "{{wezterm.inactive_tab_fg}}",
    selection_bg = "{{wezterm.selection_bg}}",
    split = "{{wezterm.split}}",
  },
}
`

const nixColorsTemplate = `# ` + generatedNotice + `
# TOML source: colors/{{source}}

{
  metadata.name = "{{metadata.name}}";
  core = {
    background = "{{core.background}}";
    darkest_bg = "{{core.darkest_bg}}";
    panel_bg = "{{core.panel_bg}}";
    ui_shadow = "{{core.ui_shadow}}";
    active_line = "{{core.active_line}}";
    selection_bg = "{{core.selection_bg}}";
    selection_fg = "{{core.selection_fg}}";
  };
  foregrounds = {
    main = "{{foregrounds.main}}";
    bright = "{{foregrounds.bright}}";
    dim = "{{foregrounds.dim}}";
    subdued = "{{foregrounds.subdued}}";
    heading = "{{foregrounds.heading}}";
  };
  teals = {
    bright = "{{teals.bright}}";
    mid_bright = "{{teals.mid_bright}}";
    standard = "{{teals.standard}}";
    muted = "{{teals.muted}}";
    deep = "{{teals.deep}}";
    border = "{{teals.border}}";
    dark_accent = "{{teals.dark_accent}}";
    sea_green = "{{teals.sea_green}}";
  };
  blues_slates = {
    slate_mid = "{{blues_slates.slate_mid}}";
    punctuation_gray = "{{blues_slates.punctuation_gray}}";
    comment_gray = "{{blues_slates.comment_gray}}";
    git_blame_gray = "{{blues_slates.git_blame_gray}}";
    slate_dark = "{{blues_slates.slate_dark}}";
    ocean_blue = "{{blues_slates.ocean_blue}}";
    sky_slate = "{{blues_slates.sky_slate}}";
    cloud_slate = "{{blues_slates.cloud_slate}}";
    deep_ocean = "{{blues_slates.deep_ocean}}";
  };
  purples = {
    lavender = "{{purples.lavender}}";
    muted_purple = "{{purples.muted_purple}}";
    bright_purple = "{{purples.bright_purple}}";
    dark_purple = "{{purples.dark_purple}}";
    deep_glitch = "{{purples.deep_glitch}}";
    soft_magenta = "{{purples.soft_magenta}}";
    dark_rose = "{{purples.dark_rose}}";
  };
  semantic = {
    success = "{{semantic.success}}";
    warning = "{{semantic.warning}}";
    error = "{{semantic.error}}";
    info = "{{semantic.info}}";
    comment = "{{semantic.comment}}";
    git_blame = "{{semantic.git_blame}}";
    string = "{{semantic.string}}";
    keyword = "{{semantic.keyword}}";
    punctuation = "{{semantic.punctuation}}";
    function = "{{semantic.function}}";
    type = "{{semantic.type}}";
    variable = "{{semantic.variable}}";
    number = "{{semantic.number}}";
    operator = "{{semantic.operator}}";
    constant = "{{semantic.constant}}";
  };
  ansi = {
    black = "{{ansi.black}}";
    red = "{{ansi.red}}";
    green = "{{ansi.green}}";
    yellow = "{{ansi.yellow}}";
    blue = "{{ansi.blue}}";
    magenta = "{{ansi.magenta}}";
    cyan = "{{ansi.cyan}}";
    white = "{{ansi.white}}";
    bright_black = "{{ansi.bright_black}}";
    bright_red = "{{ansi.bright_red}}";
    bright_green = "{{ansi.bright_green}}";
    bright_yellow = "{{ansi.bright_yellow}}";
    bright_blue = "{{ansi.bright_blue}}";
    bright_magenta = "{{ansi.bright_magenta}}";
    bright_cyan = "{{ansi.bright_cyan}}";
    bright_white = "{{ansi.bright_white}}";
  };
  nvim = {
    bg = "{{nvim.bg}}";
    dark_shadow = "{{nvim.dark_shadow}}";
    gutter_bg = "{{nvim.gutter_bg}}";
    selection = "{{nvim.selection}}";
    border = "{{nvim.border}}";
    comment = "{{nvim.comment}}";
    git_blame = "{{nvim.git_blame}}";
    punctuation = "{{nvim.punctuation}}";
    string = "{{nvim.string}}";
    keyword = "{{nvim.keyword}}";
    function = "{{nvim.function}}";
    variable = "{{nvim.variable}}";
    number = "{{nvim.number}}";
    type = "{{nvim.type}}";
    operator = "{{nvim.operator}}";
    header = "{{nvim.header}}";
    diff_add_bg = "{{nvim.diff_add_bg}}";
    diff_change_bg = "{{nvim.diff_change_bg}}";
    diff_delete_bg = "{{nvim.diff_delete_bg}}";
    diff_add_inline_bg = "{{nvim.diff_add_inline_bg}}";
    diff_change_inline_bg = "{{nvim.diff_change_inline_bg}}";
    diff_delete_inline_bg = "{{nvim.diff_delete_inline_bg}}";
  };
  zsh = {
    default = "{{zsh.default}}";
    command = "{{zsh.command}}";
    path = "{{zsh.path}}";
    string = "{{zsh.string}}";
    option = "{{zsh.option}}";
    comment = "{{zsh.comment}}";
    error = "{{zsh.error}}";
  };
}
`

const lazygitTemplate = `    # BEGIN GENERATED COLORS
    # ボーダー色
    activeBorderColor:
      - '{{teals.bright}}' # Vibrant Teal
      - bold
    inactiveBorderColor:
      - '{{teals.border}}' # UI Border (Visibility improved)
    # テキスト色
    optionsTextColor:
      - '{{foregrounds.main}}'
    defaultFgColor:
      - '{{foregrounds.main}}'
    # 選択行の背景 (Ocean Blue - 視認性と可読性のバランス)
    selectedLineBgColor:
      - '{{blues_slates.ocean_blue}}'
    selectedRangeBgColor:
      - '{{blues_slates.ocean_blue}}'
    # Git関連の色
    unstagedChangesColor:
      - '{{zsh.error}}' # Glitch Purple
    cherryPickedCommitFgColor:
      - '{{teals.bright}}'
    cherryPickedCommitBgColor:
      - '{{core.panel_bg}}' # Dark Teal Panel
  # 著者色設定
  authorColors:
    '*': '{{blues_slates.git_blame_gray}}' # Git Blame Gray (improved visibility)
    # END GENERATED COLORS
`

const ghDashTemplate = `        # BEGIN GENERATED COLORS
        text:
            primary: "{{foregrounds.main}}"
            secondary: "{{foregrounds.dim}}"
            inverted: "{{core.darkest_bg}}"
            faint: "{{foregrounds.subdued}}"
            warning: "{{semantic.warning}}"
            success: "{{semantic.success}}"
            error: "{{semantic.error}}"
            actor: "{{foregrounds.heading}}"
        background:
            selected: "{{core.active_line}}"
        border:
            primary: "{{teals.border}}"
            secondary: "{{teals.border}}"
            faint: "{{core.ui_shadow}}"
        icon:
            newcontributor: "{{semantic.success}}"
            contributor: "{{foregrounds.heading}}"
            collaborator: "{{semantic.warning}}"
            member: "{{semantic.warning}}"
            owner: "{{semantic.warning}}"
        # END GENERATED COLORS
`

const herdrTemplate = `# BEGIN GENERATED COLORS
accent = "{{ansi.blue}}"
panel_bg = "reset"
surface0 = "reset"
surface1 = "{{core.active_line}}"
surface_dim = "{{ansi.bright_black}}"
overlay0 = "{{foregrounds.dim}}"
overlay1 = "{{ansi.bright_white}}"
text = "{{foregrounds.main}}"
subtext0 = "{{foregrounds.dim}}"
mauve = "{{foregrounds.heading}}"
green = "{{ansi.green}}"
yellow = "{{ansi.yellow}}"
red = "{{ansi.bright_red}}"
blue = "{{ansi.blue}}"
teal = "{{ansi.cyan}}"
peach = "{{semantic.warning}}" # herdr 0.7.4では未使用
# END GENERATED COLORS
`

const batThemeTemplate = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>name</key>
  <string>ghost-visor</string>
  <key>settings</key>
  <array>
    <dict>
      <key>settings</key>
      <dict>
        <key>background</key>
        <string>{{core.background}}</string>
        <key>foreground</key>
        <string>{{foregrounds.main}}</string>
        <key>lineHighlight</key>
        <string>{{core.active_line}}</string>
        <key>gutterForeground</key>
        <string>{{foregrounds.dim}}</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Comment</string>
      <key>scope</key>
      <string>comment</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>{{semantic.comment}}</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>String</string>
      <key>scope</key>
      <string>string</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>{{semantic.string}}</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Numeric Constant</string>
      <key>scope</key>
      <string>constant.numeric</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>{{semantic.number}}</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Language Constant</string>
      <key>scope</key>
      <string>constant.language</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>{{semantic.constant}}</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Character Escape</string>
      <key>scope</key>
      <string>constant.character.escape</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>{{foregrounds.bright}}</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Keyword</string>
      <key>scope</key>
      <string>keyword</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>{{semantic.keyword}}</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Operator</string>
      <key>scope</key>
      <string>keyword.operator</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>{{semantic.operator}}</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Import Keyword</string>
      <key>scope</key>
      <string>keyword.control.import</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>{{teals.bright}}</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Storage Type</string>
      <key>scope</key>
      <string>storage.type</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>{{semantic.type}}</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Storage Modifier</string>
      <key>scope</key>
      <string>storage.modifier</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>{{semantic.keyword}}</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Function Declaration</string>
      <key>scope</key>
      <string>entity.name.function</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>{{semantic.function}}</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Function Call</string>
      <key>scope</key>
      <string>variable.function</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>{{semantic.function}}</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Support Function</string>
      <key>scope</key>
      <string>support.function</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>{{semantic.function}}</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Class Name</string>
      <key>scope</key>
      <string>entity.name.class</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>{{semantic.type}}</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Type Name</string>
      <key>scope</key>
      <string>entity.name.type</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>{{semantic.type}}</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Support Type</string>
      <key>scope</key>
      <string>support.type</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>{{semantic.type}}</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Tag Name</string>
      <key>scope</key>
      <string>entity.name.tag</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>{{teals.bright}}</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Attribute Name</string>
      <key>scope</key>
      <string>entity.other.attribute-name</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>{{foregrounds.heading}}</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Parameter</string>
      <key>scope</key>
      <string>variable.parameter</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>{{semantic.variable}}</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Language Variable</string>
      <key>scope</key>
      <string>variable.language</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>{{foregrounds.heading}}</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Separator Punctuation</string>
      <key>scope</key>
      <string>punctuation.separator</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>{{semantic.punctuation}}</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Terminator Punctuation</string>
      <key>scope</key>
      <string>punctuation.terminator</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>{{semantic.punctuation}}</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Section Punctuation</string>
      <key>scope</key>
      <string>punctuation.section</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>{{semantic.punctuation}}</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Definition Punctuation</string>
      <key>scope</key>
      <string>punctuation.definition</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>{{semantic.punctuation}}</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Accessor Punctuation</string>
      <key>scope</key>
      <string>punctuation.accessor</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>{{semantic.punctuation}}</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Invalid</string>
      <key>scope</key>
      <string>invalid.illegal</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>{{semantic.error}}</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>YAML Key</string>
      <key>scope</key>
      <string>entity.name.tag.yaml</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>{{teals.bright}}</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>YAML Boolean</string>
      <key>scope</key>
      <string>constant.language.boolean.yaml</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>{{semantic.keyword}}</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>YAML Null</string>
      <key>scope</key>
      <string>constant.language.null.yaml</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>{{semantic.keyword}}</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>YAML Number</string>
      <key>scope</key>
      <string>source.yaml constant.numeric</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>{{purples.lavender}}</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>YAML List Marker</string>
      <key>scope</key>
      <string>punctuation.definition.block.sequence.item.yaml</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>{{semantic.punctuation}}</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Markdown Heading</string>
      <key>scope</key>
      <string>markup.heading</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>{{foregrounds.heading}}</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Markdown Bold</string>
      <key>scope</key>
      <string>markup.bold</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>{{ansi.bright_white}}</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Markdown Italic</string>
      <key>scope</key>
      <string>markup.italic</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>{{foregrounds.bright}}</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Markdown Raw</string>
      <key>scope</key>
      <string>markup.raw</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>{{semantic.string}}</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Markdown Quote</string>
      <key>scope</key>
      <string>markup.quote</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>{{foregrounds.dim}}</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Markdown List</string>
      <key>scope</key>
      <string>markup.list</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>{{semantic.punctuation}}</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Markdown Link</string>
      <key>scope</key>
      <string>markup.underline.link</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>{{teals.bright}}</string>
      </dict>
    </dict>
  </array>
</dict>
</plist>
`

const vimTemplate = `" BEGIN GENERATED COLORS
" {{metadata.name}} カラースキーム（TOML準拠）
" ========================================

" 背景・前景（透過）
highlight Normal guibg=NONE guifg={{foregrounds.main}} ctermbg=NONE ctermfg={{xterm:foregrounds.main}}
highlight NormalNC guibg=NONE guifg={{foregrounds.main}} ctermbg=NONE ctermfg={{xterm:foregrounds.main}}
highlight NonText guibg=NONE guifg={{teals.border}} ctermbg=NONE ctermfg={{xterm:teals.border}}
highlight EndOfBuffer guibg=NONE ctermbg=NONE

" 行番号
highlight LineNr guifg={{blues_slates.comment_gray}} guibg=NONE ctermfg={{xterm:blues_slates.comment_gray}} ctermbg=NONE
highlight CursorLineNr guifg={{ansi.bright_white}} guibg=NONE ctermfg={{xterm:ansi.bright_white}} ctermbg=NONE gui=bold cterm=bold

" カーソルライン
highlight CursorLine guibg={{core.ui_shadow}} ctermbg={{xterm:core.ui_shadow}} cterm=NONE gui=NONE
highlight CursorColumn guibg={{core.ui_shadow}} ctermbg={{xterm:core.ui_shadow}}
highlight ColorColumn guibg={{core.ui_shadow}} ctermbg={{xterm:core.ui_shadow}}

" 構文ハイライト
highlight Comment guifg={{semantic.comment}} ctermfg={{xterm:semantic.comment}}
highlight Keyword guifg={{semantic.keyword}} ctermfg={{xterm:semantic.keyword}}
highlight Statement guifg={{semantic.keyword}} ctermfg={{xterm:semantic.keyword}}
highlight Conditional guifg={{semantic.keyword}} ctermfg={{xterm:semantic.keyword}}
highlight Repeat guifg={{semantic.keyword}} ctermfg={{xterm:semantic.keyword}}
highlight String guifg={{semantic.string}} ctermfg={{xterm:semantic.string}}
highlight Character guifg={{semantic.string}} ctermfg={{xterm:semantic.string}}
highlight Function guifg={{semantic.function}} ctermfg={{xterm:semantic.function}}
highlight Identifier guifg={{semantic.variable}} ctermfg={{xterm:semantic.variable}}
highlight Number guifg={{semantic.number}} ctermfg={{xterm:semantic.number}}
highlight Float guifg={{semantic.number}} ctermfg={{xterm:semantic.number}}
highlight Boolean guifg={{semantic.number}} ctermfg={{xterm:semantic.number}}
highlight Type guifg={{semantic.type}} ctermfg={{xterm:semantic.type}}
highlight Constant guifg={{semantic.constant}} ctermfg={{xterm:semantic.constant}}
highlight Operator guifg={{semantic.operator}} ctermfg={{xterm:semantic.operator}}
highlight PreProc guifg={{semantic.function}} ctermfg={{xterm:semantic.function}}
highlight Special guifg={{blues_slates.slate_mid}} ctermfg={{xterm:blues_slates.slate_mid}}
highlight Todo guifg={{semantic.function}} guibg=NONE ctermfg={{xterm:semantic.function}} ctermbg=NONE gui=bold cterm=bold

" Markdownのバッククォート（インラインコード ` + "`code`" + ` / コードフェンス ` + "```" + `）
" 既定では markdownCodeDelimiter→Delimiter→Special({{blues_slates.slate_mid}}) で暗く沈むため、
" Special自体(Conceal用途)は変えずデリミタだけ視認可能なTeal(Operator色)に上書き
highlight markdownCodeDelimiter guifg={{semantic.operator}} ctermfg={{xterm:semantic.operator}}
" 見出しの # も同根（markdownHeadingDelimiter→Delimiter→Special）で沈むため同様に上書き
highlight markdownHeadingDelimiter guifg={{semantic.operator}} ctermfg={{xterm:semantic.operator}}
highlight Underlined guifg={{semantic.function}} ctermfg={{xterm:semantic.function}} gui=underline cterm=underline
highlight Conceal guifg={{blues_slates.slate_mid}} ctermfg={{xterm:blues_slates.slate_mid}}

" UI要素
highlight SignColumn guibg=NONE ctermbg=NONE
highlight FoldColumn guibg=NONE guifg={{teals.border}} ctermbg=NONE ctermfg={{xterm:teals.border}}
highlight VertSplit guifg={{teals.border}} guibg=NONE ctermfg={{xterm:teals.border}} ctermbg=NONE
highlight StatusLine guifg={{foregrounds.main}} guibg=NONE ctermfg={{xterm:foregrounds.main}} ctermbg=NONE gui=bold cterm=bold
highlight StatusLineNC guifg={{foregrounds.subdued}} guibg=NONE ctermfg={{xterm:foregrounds.subdued}} ctermbg=NONE gui=NONE cterm=NONE
highlight TabLine guifg={{foregrounds.subdued}} guibg=NONE ctermfg={{xterm:foregrounds.subdued}} ctermbg=NONE
highlight TabLineSel guifg={{foregrounds.main}} guibg=NONE ctermfg={{xterm:foregrounds.main}} ctermbg=NONE gui=bold cterm=bold
highlight TabLineFill guibg=NONE ctermbg=NONE
highlight Visual guibg={{core.selection_bg}} guifg={{core.selection_fg}} ctermbg={{xterm:core.selection_bg}} ctermfg={{xterm:core.selection_fg}}
highlight Pmenu guibg={{core.ui_shadow}} guifg={{foregrounds.main}} ctermbg={{xterm:core.ui_shadow}} ctermfg={{xterm:foregrounds.main}}
highlight PmenuSel guibg={{core.ui_shadow}} guifg={{ansi.bright_white}} ctermbg={{xterm:core.ui_shadow}} ctermfg={{xterm:ansi.bright_white}}
highlight Search guibg={{core.ui_shadow}} guifg={{semantic.function}} ctermbg={{xterm:core.ui_shadow}} ctermfg={{xterm:semantic.function}}
highlight IncSearch guibg={{semantic.function}} guifg={{core.selection_fg}} ctermbg={{xterm:semantic.function}} ctermfg={{xterm:core.selection_fg}}
highlight MatchParen guibg={{teals.border}} guifg={{ansi.bright_white}} ctermbg={{xterm:teals.border}} ctermfg={{xterm:ansi.bright_white}} gui=bold cterm=bold

" 追加グループ
highlight Directory guifg={{semantic.function}} ctermfg={{xterm:semantic.function}}
highlight Title guifg={{foregrounds.heading}} ctermfg={{xterm:foregrounds.heading}} gui=bold cterm=bold
highlight Folded guibg={{core.ui_shadow}} guifg={{foregrounds.subdued}} ctermbg={{xterm:core.ui_shadow}} ctermfg={{xterm:foregrounds.subdued}}
highlight WildMenu guibg={{core.ui_shadow}} guifg={{ansi.bright_white}} ctermbg={{xterm:core.ui_shadow}} ctermfg={{xterm:ansi.bright_white}}
highlight Question guifg={{semantic.function}} ctermfg={{xterm:semantic.function}}
highlight MoreMsg guifg={{semantic.function}} ctermfg={{xterm:semantic.function}}
highlight ModeMsg guifg={{foregrounds.main}} ctermfg={{xterm:foregrounds.main}} gui=bold cterm=bold
highlight QuickFixLine guibg={{core.ui_shadow}} ctermbg={{xterm:core.ui_shadow}}
highlight ErrorMsg guifg={{semantic.error}} ctermfg={{xterm:semantic.error}}
highlight WarningMsg guifg={{blues_slates.cloud_slate}} ctermfg={{xterm:blues_slates.cloud_slate}}

" Diff
highlight DiffAdd guifg={{semantic.function}} guibg={{nvim.diff_add_bg}} ctermfg={{xterm:semantic.function}} ctermbg={{xterm:nvim.diff_add_bg}}
highlight DiffChange guifg={{semantic.error}} guibg={{nvim.diff_change_bg}} ctermfg={{xterm:semantic.error}} ctermbg={{xterm:nvim.diff_change_bg}}
highlight DiffDelete guifg={{foregrounds.dim}} guibg={{nvim.diff_delete_bg}} ctermfg={{xterm:foregrounds.dim}} ctermbg={{xterm:nvim.diff_delete_bg}}
highlight DiffText guifg={{foregrounds.heading}} guibg=NONE ctermfg={{xterm:foregrounds.heading}} ctermbg=NONE gui=bold cterm=bold

" スペルチェック
highlight SpellBad guifg={{semantic.error}} ctermfg={{xterm:semantic.error}} gui=undercurl cterm=underline
highlight SpellCap guifg={{blues_slates.cloud_slate}} ctermfg={{xterm:blues_slates.cloud_slate}} gui=undercurl cterm=underline
" END GENERATED COLORS
`

const statuslineANSITemplate = `# BEGIN GENERATED COLORS: ANSI
# セクション本体テキスト用前景色
C_MODEL="\e[38;2;{{rgb:foregrounds.main}}m"   # {{foregrounds.main}} foregrounds.main
C_DIR="\e[38;2;{{rgb:foregrounds.heading}}m"     # {{foregrounds.heading}} foregrounds.heading
C_GIT="\e[38;2;{{rgb:teals.bright}}m"     # {{teals.bright}} teals.bright
C_BUSY="\e[38;2;{{rgb:purples.bright_purple}}m"    # {{lower:purples.bright_purple}} purples.bright_purple

# 使用率の色（閾値で変化）
pct=${USED_PCT%.*}
pct=${pct:-0}
if [ "$pct" -gt 75 ]; then
  C_PCT="\e[38;2;{{rgb:purples.bright_purple}}m"   # {{lower:purples.bright_purple}}
elif [ "$pct" -gt 50 ]; then
  C_PCT="\e[38;2;{{rgb:purples.lavender}}m"   # {{purples.lavender}}
else
  C_PCT="\e[38;2;{{rgb:teals.mid_bright}}m"    # {{teals.mid_bright}} 安全（暗いtealは帯背景に沈む）
fi

# リミット残量の色
if [ -n "$RATE_USED" ]; then
  rate_used_int=${RATE_USED%.*}
  rate_used_int=${rate_used_int:-0}
  rate_remaining=$((100 - rate_used_int))
  if [ "$rate_remaining" -lt 25 ]; then
    C_RATE="\e[38;2;{{rgb:purples.bright_purple}}m"   # {{lower:purples.bright_purple}} 警告（purple）
  elif [ "$rate_remaining" -lt 50 ]; then
    C_RATE="\e[38;2;{{rgb:purples.lavender}}m"   # {{purples.lavender}} 注意（グレー）
  else
    C_RATE="\e[38;2;{{rgb:teals.mid_bright}}m"    # {{teals.mid_bright}} 安全（teal）
  fi
fi

# END GENERATED COLORS: ANSI
`

const statuslineSegmentsTemplate = `# BEGIN GENERATED COLORS: SEGMENTS
# --- 1段目: モデル / コンテキスト使用率 / レート制限残量 / codex・bgマーカー ---
row1=()
row1+=("{{core.darkest_bg}}|${C_MODEL}${MODEL}")
row1+=("{{nvim.gutter_bg}}|${C_PCT}󰍛 ${pct}%")
if [ -n "$RATE_USED" ]; then
  row1+=("{{core.background}}|${C_RATE}󰔛 ${rate_remaining}%")
fi
[ "$CODEX_BUSY" = "1" ] && row1+=("{{core.darkest_bg}}|${C_BUSY}󰚩")
[ "$BG_BUSY" = "1" ] && row1+=("{{core.darkest_bg}}|${C_BUSY}󰜎")

# --- 2段目: ディレクトリ / Gitブランチ ---
row2=()
row2+=("{{nvim.gutter_bg}}|${C_DIR}${DIR_NAME}")
[ -n "$GIT_BRANCH" ] && row2+=("{{core.background}}|${C_GIT}${GIT_BRANCH}")

# END GENERATED COLORS: SEGMENTS
`

const colorSystemANSITemplate = `<!-- BEGIN GENERATED COLORS -->
` + "```" + `
 0: {{ansi.black}} (Black)           8: {{ansi.bright_black}} (Bright Black)
 1: {{ansi.red}} (Red)             9: {{ansi.bright_red}} (Bright Red)
 2: {{ansi.green}} (Green)          10: {{ansi.bright_green}} (Bright Green)
 3: {{ansi.yellow}} (Yellow)         11: {{ansi.bright_yellow}} (Bright Yellow)
 4: {{ansi.blue}} (Blue)           12: {{ansi.bright_blue}} (Bright Blue)
 5: {{ansi.magenta}} (Magenta)        13: {{ansi.bright_magenta}} (Bright Magenta)
 6: {{ansi.cyan}} (Cyan)           14: {{ansi.bright_cyan}} (Bright Cyan)
 7: {{ansi.white}} (White)          15: {{ansi.bright_white}} (Bright White)
` + "```" + `
<!-- END GENERATED COLORS -->

`
