package main

import (
	"bytes"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"

	"github.com/sunagawasei/dotfiles/scripts/internal/colorutil"
	"github.com/sunagawasei/dotfiles/scripts/internal/palette"
	"github.com/sunagawasei/dotfiles/scripts/internal/xterm"
)

const generatedNotice = "GENERATED by scripts/cmd/generate-colors — DO NOT EDIT"
const markdownPreviewVendorCommit = "a923f5fc5ba36a3b17e289dc35dc17f66d0548ee"

type colorPalette struct {
	Metadata    map[string]string `toml:"metadata"`
	Core        map[string]string `toml:"core"`
	Foregrounds map[string]string `toml:"foregrounds"`
	Teals       map[string]string `toml:"teals"`
	BluesSlates map[string]string `toml:"blues_slates"`
	Purples     map[string]string `toml:"purples"`
	Semantic    map[string]string `toml:"semantic"`
	Git         map[string]string `toml:"git"`
	UI          map[string]string `toml:"ui"`
	ANSI        map[string]string `toml:"ansi"`
	WezTerm     map[string]string `toml:"wezterm"`
	Nvim        map[string]string `toml:"nvim"`
	Zsh         map[string]string `toml:"zsh"`
}

type outputFile struct {
	path    string
	content string
}

type markerOutput struct {
	path  string
	begin string
	end   string
	block string
}

type ezaStyleSpec struct {
	path           string
	token          string
	modifier       string
	completionCode string
	extensions     []string
}

var placeholderPattern = regexp.MustCompile(`\{\{(?:(lower|xterm|rgb):)?([a-z_]+)\.([a-z_]+)\}\}`)
var tokenRefPattern = regexp.MustCompile(`^[a-z_]+\.[a-z_]+$`)
var ezaPathPattern = regexp.MustCompile(`^[a-z_]+(?:\.[a-z_]+){0,2}$`)
var completionCodePattern = regexp.MustCompile(`^[A-Za-z]{2}$`)
var extensionPattern = regexp.MustCompile(`^[a-z0-9+_-]+(?:\.[a-z0-9+_-]+)*$`)

func main() {
	check := flag.Bool("check", false, "check whether generated files are up to date")
	flag.Usage = func() {
		fmt.Fprintf(flag.CommandLine.Output(), "Usage: %s [--check] [palette.toml]\n", os.Args[0])
		flag.PrintDefaults()
	}
	flag.Parse()

	if flag.NArg() > 1 {
		flag.Usage()
		os.Exit(2)
	}

	root, err := palette.FindRepositoryRoot()
	if err != nil {
		exitError(err)
	}

	palettePath, err := palette.ResolvePath(root, flag.Args())
	if err != nil {
		exitError(err)
	}

	palette, err := loadColorPalette(palettePath)
	if err != nil {
		exitError(err)
	}

	files, markers, err := generateOutputs(root, filepath.Base(palettePath), palette)
	if err != nil {
		exitError(err)
	}

	changed, err := applyOutputs(files, markers, *check)
	if err != nil {
		exitError(err)
	}
	if *check && changed {
		fmt.Fprintln(os.Stderr, "generated color files are out of date")
		os.Exit(1)
	}

	if *check {
		fmt.Println("All generated color files are up to date.")
	} else if changed {
		fmt.Printf("Generated color files from %s.\n", filepath.ToSlash(relativePath(root, palettePath)))
	} else {
		fmt.Println("Generated color files are already up to date.")
	}
}

func exitError(err error) {
	fmt.Fprintf(os.Stderr, "generate-colors: %v\n", err)
	os.Exit(1)
}

func loadColorPalette(path string) (*colorPalette, error) {
	loaded, err := palette.Load[colorPalette](path)
	if err != nil {
		var loadErr *palette.LoadError
		if errors.As(err, &loadErr) {
			switch loadErr.Stage {
			case palette.LoadStageRead:
				return nil, fmt.Errorf("read palette: %w", loadErr.Err)
			case palette.LoadStageParse:
				return nil, fmt.Errorf("parse palette: %w", loadErr.Err)
			}
		}
		return nil, err
	}
	if loaded.Metadata["name"] == "" {
		return nil, errors.New("palette metadata.name is required")
	}
	return loaded, nil
}

func (p *colorPalette) section(name string) (map[string]string, error) {
	switch name {
	case "metadata":
		return p.Metadata, nil
	case "core":
		return p.Core, nil
	case "foregrounds":
		return p.Foregrounds, nil
	case "teals":
		return p.Teals, nil
	case "blues_slates":
		return p.BluesSlates, nil
	case "purples":
		return p.Purples, nil
	case "semantic":
		return p.Semantic, nil
	case "git":
		return p.Git, nil
	case "ui":
		return p.UI, nil
	case "ansi":
		return p.ANSI, nil
	case "wezterm":
		return p.WezTerm, nil
	case "nvim":
		return p.Nvim, nil
	case "zsh":
		return p.Zsh, nil
	default:
		return nil, fmt.Errorf("unknown palette section %q", name)
	}
}

func (p *colorPalette) value(sectionName, key string) (string, error) {
	section, err := p.section(sectionName)
	if err != nil {
		return "", err
	}
	value, ok := section[key]
	if !ok || value == "" {
		return "", fmt.Errorf("missing palette value %s.%s", sectionName, key)
	}
	if sectionName != "metadata" {
		if _, _, _, err := colorutil.ParseHexRGB8(value); err != nil {
			return "", fmt.Errorf("invalid palette value %s.%s: %w", sectionName, key, err)
		}
	}
	return value, nil
}

func renderTemplate(template string, palette *colorPalette) (string, error) {
	var renderErr error
	rendered := placeholderPattern.ReplaceAllStringFunc(template, func(placeholder string) string {
		if renderErr != nil {
			return placeholder
		}
		parts := placeholderPattern.FindStringSubmatch(placeholder)
		value, err := palette.value(parts[2], parts[3])
		if err != nil {
			renderErr = err
			return placeholder
		}
		switch parts[1] {
		case "lower":
			return strings.ToLower(value)
		case "xterm":
			index, _, err := xterm.Nearest256(value)
			if err != nil {
				renderErr = err
				return placeholder
			}
			return strconv.Itoa(index)
		case "rgb":
			r, g, b, err := colorutil.ParseHexRGB8(value)
			if err != nil {
				renderErr = err
				return placeholder
			}
			return fmt.Sprintf("%d;%d;%d", r, g, b)
		default:
			return value
		}
	})
	if renderErr != nil {
		return "", renderErr
	}
	return rendered, nil
}

func parseEzaStyleSpecs(template string) ([]ezaStyleSpec, error) {
	var specs []ezaStyleSpec
	seenPaths := make(map[string]bool)
	seenCodes := make(map[string]bool)
	seenExtensions := make(map[string]bool)
	for lineNumber, rawLine := range strings.Split(template, "\n") {
		line := strings.TrimSpace(rawLine)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		fields := strings.Split(line, "|")
		if len(fields) != 5 {
			return nil, fmt.Errorf("eza style spec line %d has %d fields, want 5", lineNumber+1, len(fields))
		}
		for index := range fields {
			fields[index] = strings.TrimSpace(fields[index])
		}
		spec := ezaStyleSpec{
			path:           fields[0],
			token:          fields[1],
			modifier:       fields[2],
			completionCode: fields[3],
		}
		if !ezaPathPattern.MatchString(spec.path) {
			return nil, fmt.Errorf("eza style spec line %d has invalid path %q", lineNumber+1, spec.path)
		}
		if seenPaths[spec.path] {
			return nil, fmt.Errorf("eza style spec line %d duplicates path %q", lineNumber+1, spec.path)
		}
		seenPaths[spec.path] = true
		if !tokenRefPattern.MatchString(spec.token) {
			return nil, fmt.Errorf("eza style spec line %d has invalid token %q", lineNumber+1, spec.token)
		}
		if spec.modifier != "" && spec.modifier != "bold" {
			return nil, fmt.Errorf("eza style spec line %d has unknown modifier %q", lineNumber+1, spec.modifier)
		}
		if spec.completionCode != "" {
			if !completionCodePattern.MatchString(spec.completionCode) {
				return nil, fmt.Errorf("eza style spec line %d has invalid completion code %q", lineNumber+1, spec.completionCode)
			}
			if seenCodes[spec.completionCode] {
				return nil, fmt.Errorf("eza style spec line %d duplicates completion code %q", lineNumber+1, spec.completionCode)
			}
			seenCodes[spec.completionCode] = true
		}
		if fields[4] != "" {
			for _, extension := range strings.Split(fields[4], ",") {
				extension = strings.TrimSpace(extension)
				if !extensionPattern.MatchString(extension) {
					return nil, fmt.Errorf("eza style spec line %d has invalid extension %q", lineNumber+1, extension)
				}
				if seenExtensions[extension] {
					return nil, fmt.Errorf("eza style spec line %d duplicates extension %q", lineNumber+1, extension)
				}
				seenExtensions[extension] = true
				spec.extensions = append(spec.extensions, extension)
			}
		}
		if len(spec.extensions) > 0 && !strings.HasPrefix(spec.path, "file_type.") {
			return nil, fmt.Errorf("eza style spec line %d assigns extensions to non-file_type path %q", lineNumber+1, spec.path)
		}
		specs = append(specs, spec)
	}
	if len(specs) == 0 {
		return nil, errors.New("eza style spec template is empty")
	}
	return specs, nil
}

func buildEzaThemeTemplate(specs []ezaStyleSpec) string {
	var builder strings.Builder
	builder.WriteString("# " + generatedNotice + "\n")
	builder.WriteString("# eza 0.23.4 UiStyles schema; all visible Style keys are explicit.\n")
	builder.WriteString("colourful: true\n")

	var previousParents []string
	for _, spec := range specs {
		parts := strings.Split(spec.path, ".")
		parents := parts[:len(parts)-1]
		common := 0
		for common < len(parents) && common < len(previousParents) && parents[common] == previousParents[common] {
			common++
		}
		for index := common; index < len(parents); index++ {
			fmt.Fprintf(&builder, "%s%s:\n", strings.Repeat("  ", index), parents[index])
		}
		indent := strings.Repeat("  ", len(parents))
		fmt.Fprintf(&builder, "%s%s:\n", indent, parts[len(parts)-1])
		fmt.Fprintf(&builder, "%s  foreground: \"{{%s}}\"\n", indent, spec.token)
		if spec.modifier == "bold" {
			fmt.Fprintf(&builder, "%s  is_bold: true\n", indent)
		}
		previousParents = parents
	}
	builder.WriteString("filenames: {}\n")
	builder.WriteString("extensions: {}\n")
	return builder.String()
}

func buildZshCompletionTemplate(specs []ezaStyleSpec) string {
	entries := []string{
		"ma=48;2;{{rgb:core.selection_bg}};38;2;{{rgb:core.selection_fg}}",
	}
	for _, spec := range specs {
		if spec.completionCode != "" {
			entries = append(entries, spec.completionCode+"=38;2;{{rgb:"+spec.token+"}}")
		}
		for _, extension := range spec.extensions {
			entries = append(entries, "*."+extension+"=38;2;{{rgb:"+spec.token+"}}")
		}
	}

	var builder strings.Builder
	builder.WriteString("        # BEGIN GENERATED COLORS: ZSH COMPLETION\n")
	builder.WriteString("        # LS_COLORS overrides eza/theme.yml, so discard inherited values in interactive shells.\n")
	builder.WriteString("        # Non-interactive shells do not read this block; scripts invoking eza must unset LS_COLORS themselves.\n")
	builder.WriteString("        unset LS_COLORS\n")
	builder.WriteString("        typeset -ga ZSH_COMPLETION_COLORS=(\n")
	for _, entry := range entries {
		fmt.Fprintf(&builder, "          '%s'\n", entry)
	}
	builder.WriteString("        )\n")
	builder.WriteString("        # END GENERATED COLORS: ZSH COMPLETION\n")
	return builder.String()
}

func generateOutputs(root, sourceName string, palette *colorPalette) ([]outputFile, []markerOutput, error) {
	if err := validateMarkdownPreviewVendorCommit(root); err != nil {
		return nil, nil, err
	}

	ezaSpecs, err := parseEzaStyleSpecs(ezaStyleSpecTemplate)
	if err != nil {
		return nil, nil, err
	}
	ezaThemeTemplate := buildEzaThemeTemplate(ezaSpecs)
	zshCompletionTemplate := buildZshCompletionTemplate(ezaSpecs)

	templates := []struct {
		path     string
		template string
	}{
		{filepath.Join(root, "nvim/lua/config/palette.lua"), paletteLuaTemplate},
		{filepath.Join(root, "wezterm/colors.lua"), weztermLuaTemplate},
		{filepath.Join(root, "home-manager/colors.nix"), nixColorsTemplate},
		{filepath.Join(root, "claude/themes/ghost-visor.json"), claudeThemeTemplate},
		{filepath.Join(root, "bat/themes/ghost-visor.tmTheme"), batThemeTemplate},
		{filepath.Join(root, "eza/theme.yml"), ezaThemeTemplate},
		{filepath.Join(root, "nvim/generated/mkdp-markdown.css"), markdownPreviewMarkdownTemplate},
		{filepath.Join(root, "nvim/generated/mkdp-highlight.css"), markdownPreviewHighlightTemplate},
	}

	files := make([]outputFile, 0, len(templates))
	for _, item := range templates {
		template := strings.ReplaceAll(item.template, "{{source}}", sourceName)
		content, err := renderTemplate(template, palette)
		if err != nil {
			return nil, nil, fmt.Errorf("render %s: %w", relativePath(root, item.path), err)
		}
		files = append(files, outputFile{path: item.path, content: content})
	}

	markerTemplates := []struct {
		path     string
		begin    string
		end      string
		template string
	}{
		{
			path: filepath.Join(root, "lazygit/config.yml"), begin: "    # BEGIN GENERATED COLORS", end: "    # END GENERATED COLORS",
			template: lazygitTemplate,
		},
		{
			path: filepath.Join(root, "gh-dash/config.yml"), begin: "        # BEGIN GENERATED COLORS", end: "        # END GENERATED COLORS",
			template: ghDashTemplate,
		},
		{
			path: filepath.Join(root, "herdr/config.toml"), begin: "# BEGIN GENERATED COLORS", end: "# END GENERATED COLORS",
			template: herdrTemplate,
		},
		{
			path: filepath.Join(root, "home-manager/zsh.nix"), begin: "        # BEGIN GENERATED COLORS: ZSH COMPLETION", end: "        # END GENERATED COLORS: ZSH COMPLETION",
			template: zshCompletionTemplate,
		},
		{
			path: filepath.Join(root, "vim/vimrc"), begin: `" BEGIN GENERATED COLORS`, end: `" END GENERATED COLORS`,
			template: vimTemplate,
		},
		{
			path: filepath.Join(root, "claude/statusline.sh"), begin: "# BEGIN GENERATED COLORS: ANSI", end: "# END GENERATED COLORS: ANSI",
			template: statuslineANSITemplate,
		},
		{
			path: filepath.Join(root, "claude/statusline.sh"), begin: "# BEGIN GENERATED COLORS: SEGMENTS", end: "# END GENERATED COLORS: SEGMENTS",
			template: statuslineSegmentsTemplate,
		},
		{
			path: filepath.Join(root, "COLOR-SYSTEM.md"), begin: "<!-- BEGIN GENERATED COLORS -->", end: "<!-- END GENERATED COLORS -->",
			template: colorSystemANSITemplate,
		},
	}

	markers := make([]markerOutput, 0, len(markerTemplates))
	for _, item := range markerTemplates {
		block, err := renderTemplate(item.template, palette)
		if err != nil {
			return nil, nil, fmt.Errorf("render marker block for %s: %w", relativePath(root, item.path), err)
		}
		markers = append(markers, markerOutput{path: item.path, begin: item.begin, end: item.end, block: block})
	}
	return files, markers, nil
}

func validateMarkdownPreviewVendorCommit(root string) error {
	data, err := os.ReadFile(filepath.Join(root, "nvim", "lazy-lock.json"))
	if err != nil {
		return fmt.Errorf("read markdown-preview lock: %w", err)
	}
	return validateMarkdownPreviewVendorLock(data)
}

func validateMarkdownPreviewVendorLock(data []byte) error {
	var lock map[string]struct {
		Commit string `json:"commit"`
	}
	if err := json.Unmarshal(data, &lock); err != nil {
		return fmt.Errorf("parse markdown-preview lock: %w", err)
	}
	entry, ok := lock["markdown-preview.nvim"]
	if !ok || entry.Commit == "" {
		return errors.New("markdown-preview.nvim is missing from nvim/lazy-lock.json")
	}
	if entry.Commit != markdownPreviewVendorCommit {
		return fmt.Errorf(
			"markdown-preview.nvim is locked at %s, but vendored CSS targets %s; rebase the vendored base CSS onto the new upstream commit",
			entry.Commit,
			markdownPreviewVendorCommit,
		)
	}
	return nil
}

func applyOutputs(files []outputFile, markers []markerOutput, check bool) (bool, error) {
	expected := make(map[string]string, len(files)+len(markers))
	for _, file := range files {
		expected[file.path] = file.content
	}

	for _, marker := range markers {
		content, ok := expected[marker.path]
		if !ok {
			data, err := os.ReadFile(marker.path)
			if err != nil {
				return false, fmt.Errorf("read %s: %w", marker.path, err)
			}
			content = string(data)
		}
		updated, err := replaceGeneratedBlock(content, marker)
		if err != nil {
			return false, err
		}
		expected[marker.path] = updated
	}

	paths := make([]string, 0, len(expected))
	for path := range expected {
		paths = append(paths, path)
	}
	sort.Strings(paths)

	changed := false
	for _, path := range paths {
		actual, err := os.ReadFile(path)
		if err != nil && !os.IsNotExist(err) {
			return false, fmt.Errorf("read %s: %w", path, err)
		}
		want := []byte(expected[path])
		if bytes.Equal(actual, want) {
			continue
		}
		changed = true
		if check {
			if err := printUnifiedDiff(path, actual, want); err != nil {
				return false, err
			}
			continue
		}
		if err := writePreservingMode(path, want); err != nil {
			return false, err
		}
		fmt.Printf("updated %s\n", path)
	}
	return changed, nil
}

func replaceGeneratedBlock(content string, marker markerOutput) (string, error) {
	beginIndex := strings.Index(content, marker.begin)
	if beginIndex >= 0 {
		endRelative := strings.Index(content[beginIndex:], marker.end)
		if endRelative < 0 {
			return "", fmt.Errorf("missing end marker %q in %s", marker.end, marker.path)
		}
		endIndex := beginIndex + endRelative + len(marker.end)
		for endIndex < len(content) && content[endIndex] == '\n' {
			endIndex++
		}
		return content[:beginIndex] + marker.block + content[endIndex:], nil
	}

	return "", fmt.Errorf("missing start marker %q in %s", marker.begin, marker.path)
}

func writePreservingMode(path string, content []byte) error {
	mode := os.FileMode(0o644)
	if info, err := os.Stat(path); err == nil {
		mode = info.Mode().Perm()
	} else if !os.IsNotExist(err) {
		return fmt.Errorf("stat %s: %w", path, err)
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("create parent directory for %s: %w", path, err)
	}
	if err := os.WriteFile(path, content, mode); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	return nil
}

func printUnifiedDiff(path string, actual, expected []byte) error {
	actualFile, err := os.CreateTemp("", "generate-colors-actual-*")
	if err != nil {
		return fmt.Errorf("create diff input: %w", err)
	}
	defer os.Remove(actualFile.Name())
	if _, err := actualFile.Write(actual); err != nil {
		actualFile.Close()
		return fmt.Errorf("write diff input: %w", err)
	}
	if err := actualFile.Close(); err != nil {
		return fmt.Errorf("close diff input: %w", err)
	}

	expectedFile, err := os.CreateTemp("", "generate-colors-expected-*")
	if err != nil {
		return fmt.Errorf("create diff input: %w", err)
	}
	defer os.Remove(expectedFile.Name())
	if _, err := expectedFile.Write(expected); err != nil {
		expectedFile.Close()
		return fmt.Errorf("write diff input: %w", err)
	}
	if err := expectedFile.Close(); err != nil {
		return fmt.Errorf("close diff input: %w", err)
	}

	cmd := exec.Command("diff", "-u", "--label", path, "--label", path+" (generated)", actualFile.Name(), expectedFile.Name())
	output, err := cmd.CombinedOutput()
	if len(output) > 0 {
		fmt.Fprint(os.Stderr, string(output))
	}
	var exitErr *exec.ExitError
	if err != nil && (!errors.As(err, &exitErr) || exitErr.ExitCode() != 1) {
		return fmt.Errorf("diff %s: %w", path, err)
	}
	return nil
}

func relativePath(root, path string) string {
	relative, err := filepath.Rel(root, path)
	if err != nil {
		return path
	}
	return relative
}

// claudeThemeTemplate derives the Claude Code theme from existing ghost-visor.toml keys.
// Changes to shared keys such as ansi.*, nvim.*, and core.* must flow through to this theme.
// name and base remain literals because they are Claude Code-specific values.
const claudeThemeTemplate = `{
  "name": "Ghost Visor",
  "base": "dark-ansi",
  "overrides": {
    "claude": "{{teals.bright}}",
    "claudeShimmer": "{{foregrounds.bright}}",
    "claudeBlue_FOR_SYSTEM_SPINNER": "{{teals.bright}}",
    "claudeBlueShimmer_FOR_SYSTEM_SPINNER": "{{foregrounds.bright}}",
    "text": "{{foregrounds.main}}",
    "inverseText": "{{core.darkest_bg}}",
    "inactive": "{{foregrounds.dim}}",
    "inactiveShimmer": "{{blues_slates.cloud_slate}}",
    "subtle": "{{foregrounds.subdued}}",
    "suggestion": "{{teals.mid_bright}}",
    "permission": "{{teals.border}}",
    "permissionShimmer": "{{teals.bright}}",
    "remember": "{{purples.bright_purple}}",
    "skill": "{{purples.bright_purple}}",
    "effortUltra": "{{purples.bright_purple}}",
    "chromeYellow": "{{ansi.bright_yellow}}",
    "professionalBlue": "{{ansi.blue}}",
    "success": "{{semantic.success}}",
    "error": "{{ansi.magenta}}",
    "warning": "{{ansi.yellow}}",
    "warningShimmer": "{{ansi.bright_yellow}}",
    "merged": "{{purples.bright_purple}}",
    "promptBorder": "{{teals.border}}",
    "promptBorderShimmer": "{{teals.bright}}",
    "planMode": "{{teals.bright}}",
    "autoAccept": "{{semantic.success}}",
    "autoAcceptShimmer": "{{foregrounds.bright}}",
    "bashBorder": "{{ansi.magenta}}",
    "ide": "{{teals.bright}}",
    "fastMode": "{{ansi.bright_magenta}}",
    "fastModeShimmer": "{{ansi.bright_white}}",
    "diffAdded": "{{nvim.diff_add_bg}}",
    "diffRemoved": "{{nvim.diff_delete_bg}}",
    "diffAddedDimmed": "{{nvim.gutter_bg}}",
    "diffRemovedDimmed": "{{core.ui_shadow}}",
    "diffAddedWord": "{{nvim.diff_add_inline_bg}}",
    "diffRemovedWord": "{{nvim.diff_delete_inline_bg}}",
    "userMessageBackground": "{{core.ui_shadow}}",
    "userMessageBackgroundHover": "{{core.active_line}}",
    "bashMessageBackgroundColor": "{{purples.dark_rose}}",
    "memoryBackgroundColor": "{{nvim.diff_change_bg}}",
    "selectionBg": "{{blues_slates.slate_dark}}",
    "rate_limit_fill": "{{teals.bright}}",
    "rate_limit_empty": "{{core.ui_shadow}}",
    "briefLabelYou": "{{foregrounds.dim}}",
    "briefLabelClaude": "{{teals.bright}}"
  }
}
`

const paletteLuaTemplate = `-- ` + generatedNotice + `
-- {{metadata.name}} カラーパレット共有モジュール
-- TOMLソース: colors/{{source}}
-- 単一ソース原則: このモジュールから全プラグイン設定が色を参照する

local M = {}

M.colors = {
  -- コアカラー
  bg = "{{core.background}}",           -- Main (Pure Black) [core.background]
  darkest_bg = "{{core.darkest_bg}}",   -- Deepest Shadow [core.darkest_bg]
  panel_bg = "{{core.panel_bg}}",     -- Dark Teal Panel [core.panel_bg]
  dark_shadow = "{{core.ui_shadow}}",  -- UI Shadow [core.ui_shadow]
  gutter_bg = "{{nvim.gutter_bg}}",    -- Gutter background [nvim.gutter_bg]
  border = "{{teals.border}}",       -- UI Border [teals.border]
  mid_gray = "{{blues_slates.slate_mid}}",     -- Background fill / intentional dim only [blues_slates.slate_mid]
  subdued_fg = "{{foregrounds.subdued}}",   -- Subdued foreground [foregrounds.subdued]
  light_gray = "{{foregrounds.dim}}",   -- Dim text [foregrounds.dim]

  -- Visibility improvements
  punctuation_gray = "{{blues_slates.punctuation_gray}}",  -- 句読点 [blues_slates.punctuation_gray]
  comment_gray = "{{blues_slates.comment_gray}}",      -- コメント [blues_slates.comment_gray]
  git_blame_gray = "{{blues_slates.git_blame_gray}}",    -- Git blame [blues_slates.git_blame_gray]
  operator = "{{teals.mid_bright}}",     -- Clear Teal [teals.mid_bright]
  fg = "{{foregrounds.main}}",           -- Main Text [foregrounds.main]
  foreground_bright = "{{foregrounds.bright}}",   -- Bright foreground [foregrounds.bright]
  highlight_white = "{{ansi.bright_white}}", -- Purest [ansi.bright_white]

  -- アクセントカラー
  teal_bright = "{{teals.bright}}",         -- Bright Teal [teals.bright]
  foreground_heading = "{{foregrounds.heading}}",  -- Heading foreground [foregrounds.heading]
  cloud_slate = "{{blues_slates.cloud_slate}}", -- Cloud Slate [blues_slates.cloud_slate]

  -- 拡張セマンティック
  purple_accent = "{{purples.muted_purple}}", -- Muted Purple (Keyword) [purples.muted_purple]
  syntax_violet = "{{semantic.keyword}}", -- Syntax Violet [semantic.keyword]
  syntax_function = "{{semantic.function}}", -- Syntax function [semantic.function]
  syntax_type = "{{semantic.type}}", -- Syntax type [semantic.type]
  syntax_number = "{{semantic.number}}", -- Syntax number [semantic.number]
  syntax_constant = "{{semantic.constant}}", -- Syntax constant [semantic.constant]
  syntax_variable = "{{semantic.variable}}", -- Syntax variable [semantic.variable]
  syntax_builtin_variable = "{{semantic.builtin_variable}}", -- Syntax builtin variable [semantic.builtin_variable]
  success = "{{semantic.success}}",       -- Success indicator [semantic.success]
  diagnostic_error = "{{semantic.error}}", -- Diagnostic error [semantic.error]
  diagnostic_warn = "{{semantic.warning}}", -- Diagnostic warning [semantic.warning]
  diagnostic_info = "{{semantic.info}}", -- Diagnostic info [semantic.info]
  diagnostic_hint = "{{semantic.hint}}", -- Diagnostic hint [semantic.hint]
  git_added = "{{git.added}}",         -- Git added [git.added]
  git_changed = "{{git.changed}}",     -- Git changed [git.changed]
  git_deleted = "{{git.deleted}}",     -- Git deleted [git.deleted]
  ui_target_bg = "{{ui.target_bg}}",   -- UI target background [ui.target_bg]
  ui_accent_fg = "{{ui.accent_fg}}",   -- UI ambient accent [ui.accent_fg]
  ocean_blue = "{{blues_slates.ocean_blue}}",    -- Ocean Blue [blues_slates.ocean_blue]
  lavender = "{{purples.lavender}}",      -- Lavender (Constant) [purples.lavender]

  -- ANSI/Terminal
  ansi_black = "{{ansi.black}}", -- ANSI Black [ansi.black]
  ansi_red = "{{ansi.red}}", -- ANSI Red [ansi.red]
  ansi_green = "{{ansi.green}}", -- ANSI Green [ansi.green]
  ansi_yellow = "{{ansi.yellow}}", -- ANSI Yellow [ansi.yellow]
  ansi_blue = "{{ansi.blue}}", -- ANSI Blue [ansi.blue]
  ansi_magenta = "{{ansi.magenta}}", -- ANSI Magenta [ansi.magenta]
  ansi_cyan = "{{ansi.cyan}}", -- ANSI Cyan [ansi.cyan]
  ansi_white = "{{ansi.white}}", -- ANSI White [ansi.white]
  ansi_bright_black = "{{ansi.bright_black}}", -- ANSI Bright Black [ansi.bright_black]
  ansi_bright_red = "{{ansi.bright_red}}", -- ANSI Bright Red [ansi.bright_red]
  ansi_bright_green = "{{ansi.bright_green}}", -- ANSI Bright Green [ansi.bright_green]
  ansi_bright_yellow = "{{ansi.bright_yellow}}", -- ANSI Bright Yellow [ansi.bright_yellow]
  ansi_bright_blue = "{{ansi.bright_blue}}", -- ANSI Bright Blue [ansi.bright_blue]
  ansi_bright_magenta = "{{ansi.bright_magenta}}", -- ANSI Bright Magenta [ansi.bright_magenta]
  ansi_bright_cyan = "{{ansi.bright_cyan}}", -- ANSI Bright Cyan [ansi.bright_cyan]
  ansi_bright_white = "{{ansi.bright_white}}", -- ANSI Bright White [ansi.bright_white]

  -- その他
  sky_slate = "{{blues_slates.sky_slate}}",        -- Sky Slate (Icon) [blues_slates.sky_slate]
  selection = "{{core.selection_bg}}",    -- Clear Teal [core.selection_bg]
  selection_fg = "{{core.selection_fg}}", -- Background for contrast
  string = "{{semantic.string}}",       -- Base Teal [semantic.string]

  -- Diff背景カラー
  diff_add_bg = "{{nvim.diff_add_bg}}",      -- Diff Add背景 [nvim.diff_add_bg]
  diff_change_bg = "{{nvim.diff_change_bg}}",   -- Diff Change背景 [nvim.diff_change_bg]
  diff_delete_bg = "{{nvim.diff_delete_bg}}",   -- Diff Delete背景 [nvim.diff_delete_bg]
  diff_add_inline_bg = "{{nvim.diff_add_inline_bg}}",     -- Word-diff add背景 [nvim.diff_add_inline_bg]
  diff_change_inline_bg = "{{nvim.diff_change_inline_bg}}",  -- Word-diff change背景 [nvim.diff_change_inline_bg]
  diff_delete_inline_bg = "{{nvim.diff_delete_inline_bg}}",  -- Word-diff delete背景 [nvim.diff_delete_inline_bg]
}

return M
`

const weztermLuaTemplate = `-- ` + generatedNotice + `
-- TOML source: colors/{{source}}

return {
  metadata = { name = "{{metadata.name}}" },
  core = {
    background = "{{core.background}}",
    darkest_bg = "{{core.darkest_bg}}",
    panel_bg = "{{core.panel_bg}}",
    ui_shadow = "{{core.ui_shadow}}",
    active_line = "{{core.active_line}}",
    selection_bg = "{{core.selection_bg}}",
    selection_fg = "{{core.selection_fg}}",
  },
  foregrounds = {
    main = "{{foregrounds.main}}",
    bright = "{{foregrounds.bright}}",
    dim = "{{foregrounds.dim}}",
    subdued = "{{foregrounds.subdued}}",
    heading = "{{foregrounds.heading}}",
  },
  teals = {
    bright = "{{teals.bright}}",
    mid_bright = "{{teals.mid_bright}}",
    standard = "{{teals.standard}}",
    muted = "{{teals.muted}}",
    deep = "{{teals.deep}}",
    border = "{{teals.border}}",
    dark_accent = "{{teals.dark_accent}}",
    sea_green = "{{teals.sea_green}}",
  },
  blues_slates = {
    slate_mid = "{{blues_slates.slate_mid}}",
    punctuation_gray = "{{blues_slates.punctuation_gray}}",
    comment_gray = "{{blues_slates.comment_gray}}",
    git_blame_gray = "{{blues_slates.git_blame_gray}}",
    slate_dark = "{{blues_slates.slate_dark}}",
    ocean_blue = "{{blues_slates.ocean_blue}}",
    sky_slate = "{{blues_slates.sky_slate}}",
    cloud_slate = "{{blues_slates.cloud_slate}}",
    deep_ocean = "{{blues_slates.deep_ocean}}",
  },
  purples = {
    lavender = "{{purples.lavender}}",
    muted_purple = "{{purples.muted_purple}}",
    bright_purple = "{{purples.bright_purple}}",
    dark_purple = "{{purples.dark_purple}}",
    deep_glitch = "{{purples.deep_glitch}}",
    soft_magenta = "{{purples.soft_magenta}}",
    dark_rose = "{{purples.dark_rose}}",
  },
  semantic = {
    success = "{{semantic.success}}",
    warning = "{{semantic.warning}}",
    error = "{{semantic.error}}",
    info = "{{semantic.info}}",
    hint = "{{semantic.hint}}",
    comment = "{{semantic.comment}}",
    git_blame = "{{semantic.git_blame}}",
    string = "{{semantic.string}}",
    keyword = "{{semantic.keyword}}",
    punctuation = "{{semantic.punctuation}}",
    function_color = "{{semantic.function}}",
    type_color = "{{semantic.type}}",
    variable = "{{semantic.variable}}",
    builtin_variable = "{{semantic.builtin_variable}}",
    number = "{{semantic.number}}",
    operator = "{{semantic.operator}}",
    constant = "{{semantic.constant}}",
  },
  ansi = {
    black = "{{ansi.black}}",
    red = "{{ansi.red}}",
    green = "{{ansi.green}}",
    yellow = "{{ansi.yellow}}",
    blue = "{{ansi.blue}}",
    magenta = "{{ansi.magenta}}",
    cyan = "{{ansi.cyan}}",
    white = "{{ansi.white}}",
    bright_black = "{{ansi.bright_black}}",
    bright_red = "{{ansi.bright_red}}",
    bright_green = "{{ansi.bright_green}}",
    bright_yellow = "{{ansi.bright_yellow}}",
    bright_blue = "{{ansi.bright_blue}}",
    bright_magenta = "{{ansi.bright_magenta}}",
    bright_cyan = "{{ansi.bright_cyan}}",
    bright_white = "{{ansi.bright_white}}",
  },
  wezterm = {
    background = "{{wezterm.background}}",
    tab_bar = "{{wezterm.tab_bar}}",
    active_tab = "{{wezterm.active_tab}}",
    inactive_tab = "{{wezterm.inactive_tab}}",
    active_tab_fg = "{{wezterm.active_tab_fg}}",
    inactive_tab_fg = "{{wezterm.inactive_tab_fg}}",
    selection_bg = "{{wezterm.selection_bg}}",
    split = "{{wezterm.split}}",
  },
}
`

const nixColorsTemplate = `# ` + generatedNotice + `
# TOML source: colors/{{source}}

{
  metadata.name = "{{metadata.name}}";
  core = {
    background = "{{core.background}}";
    darkest_bg = "{{core.darkest_bg}}";
    panel_bg = "{{core.panel_bg}}";
    ui_shadow = "{{core.ui_shadow}}";
    active_line = "{{core.active_line}}";
    selection_bg = "{{core.selection_bg}}";
    selection_fg = "{{core.selection_fg}}";
  };
  foregrounds = {
    main = "{{foregrounds.main}}";
    bright = "{{foregrounds.bright}}";
    dim = "{{foregrounds.dim}}";
    subdued = "{{foregrounds.subdued}}";
    heading = "{{foregrounds.heading}}";
  };
  teals = {
    bright = "{{teals.bright}}";
    mid_bright = "{{teals.mid_bright}}";
    standard = "{{teals.standard}}";
    muted = "{{teals.muted}}";
    deep = "{{teals.deep}}";
    border = "{{teals.border}}";
    dark_accent = "{{teals.dark_accent}}";
    sea_green = "{{teals.sea_green}}";
  };
  blues_slates = {
    slate_mid = "{{blues_slates.slate_mid}}";
    punctuation_gray = "{{blues_slates.punctuation_gray}}";
    comment_gray = "{{blues_slates.comment_gray}}";
    git_blame_gray = "{{blues_slates.git_blame_gray}}";
    slate_dark = "{{blues_slates.slate_dark}}";
    ocean_blue = "{{blues_slates.ocean_blue}}";
    sky_slate = "{{blues_slates.sky_slate}}";
    cloud_slate = "{{blues_slates.cloud_slate}}";
    deep_ocean = "{{blues_slates.deep_ocean}}";
  };
  purples = {
    lavender = "{{purples.lavender}}";
    muted_purple = "{{purples.muted_purple}}";
    bright_purple = "{{purples.bright_purple}}";
    dark_purple = "{{purples.dark_purple}}";
    deep_glitch = "{{purples.deep_glitch}}";
    soft_magenta = "{{purples.soft_magenta}}";
    dark_rose = "{{purples.dark_rose}}";
  };
  semantic = {
    success = "{{semantic.success}}";
    warning = "{{semantic.warning}}";
    error = "{{semantic.error}}";
    info = "{{semantic.info}}";
    hint = "{{semantic.hint}}";
    comment = "{{semantic.comment}}";
    git_blame = "{{semantic.git_blame}}";
    string = "{{semantic.string}}";
    keyword = "{{semantic.keyword}}";
    punctuation = "{{semantic.punctuation}}";
    function = "{{semantic.function}}";
    type = "{{semantic.type}}";
    variable = "{{semantic.variable}}";
    builtin_variable = "{{semantic.builtin_variable}}";
    number = "{{semantic.number}}";
    operator = "{{semantic.operator}}";
    constant = "{{semantic.constant}}";
  };
  git = {
    added = "{{git.added}}";
    changed = "{{git.changed}}";
    deleted = "{{git.deleted}}";
  };
  ui = {
    target_bg = "{{ui.target_bg}}";
    accent_fg = "{{ui.accent_fg}}";
  };
  ansi = {
    black = "{{ansi.black}}";
    red = "{{ansi.red}}";
    green = "{{ansi.green}}";
    yellow = "{{ansi.yellow}}";
    blue = "{{ansi.blue}}";
    magenta = "{{ansi.magenta}}";
    cyan = "{{ansi.cyan}}";
    white = "{{ansi.white}}";
    bright_black = "{{ansi.bright_black}}";
    bright_red = "{{ansi.bright_red}}";
    bright_green = "{{ansi.bright_green}}";
    bright_yellow = "{{ansi.bright_yellow}}";
    bright_blue = "{{ansi.bright_blue}}";
    bright_magenta = "{{ansi.bright_magenta}}";
    bright_cyan = "{{ansi.bright_cyan}}";
    bright_white = "{{ansi.bright_white}}";
  };
  nvim = {
    bg = "{{nvim.bg}}";
    dark_shadow = "{{nvim.dark_shadow}}";
    gutter_bg = "{{nvim.gutter_bg}}";
    selection = "{{nvim.selection}}";
    border = "{{nvim.border}}";
    comment = "{{nvim.comment}}";
    git_blame = "{{nvim.git_blame}}";
    punctuation = "{{nvim.punctuation}}";
    string = "{{nvim.string}}";
    keyword = "{{nvim.keyword}}";
    function = "{{nvim.function}}";
    variable = "{{nvim.variable}}";
    number = "{{nvim.number}}";
    type = "{{nvim.type}}";
    operator = "{{nvim.operator}}";
    header = "{{nvim.header}}";
    diff_add_bg = "{{nvim.diff_add_bg}}";
    diff_change_bg = "{{nvim.diff_change_bg}}";
    diff_delete_bg = "{{nvim.diff_delete_bg}}";
    diff_add_inline_bg = "{{nvim.diff_add_inline_bg}}";
    diff_change_inline_bg = "{{nvim.diff_change_inline_bg}}";
    diff_delete_inline_bg = "{{nvim.diff_delete_inline_bg}}";
  };
  zsh = {
    default = "{{zsh.default}}";
    command = "{{zsh.command}}";
    path = "{{zsh.path}}";
    string = "{{zsh.string}}";
    option = "{{zsh.option}}";
    comment = "{{zsh.comment}}";
  };
}
`

// ezaStyleSpecTemplate is the shared source for eza's UiStyles and the subset
// representable by zsh list-colors. Format: path|token|modifier|code|extensions.
const ezaStyleSpecTemplate = `
filekinds.normal|foregrounds.main||fi|
filekinds.directory|foregrounds.heading||di|
filekinds.symlink|semantic.keyword||ln|
filekinds.pipe|semantic.operator||pi|
filekinds.block_device|foregrounds.dim||bd|
filekinds.char_device|foregrounds.dim||cd|
filekinds.socket|semantic.operator||so|
filekinds.special|teals.mid_bright|||
filekinds.executable|semantic.success||ex|
filekinds.mount_point|teals.mid_bright|||
perms.user_read|foregrounds.dim|||
perms.user_write|semantic.warning|||
perms.user_execute_file|semantic.success|||
perms.user_execute_other|semantic.success|||
perms.group_read|foregrounds.dim|||
perms.group_write|semantic.warning|||
perms.group_execute|semantic.success|||
perms.other_read|foregrounds.dim|||
perms.other_write|semantic.warning|||
perms.other_execute|semantic.success|||
perms.special_user_file|purples.bright_purple|||
perms.special_other|purples.bright_purple|||
perms.attribute|foregrounds.subdued|||
size.major|foregrounds.dim|||
size.minor|foregrounds.dim|||
size.number_byte|foregrounds.main|||
size.number_kilo|foregrounds.main|||
size.number_mega|foregrounds.main|||
size.number_giga|foregrounds.main|||
size.number_huge|foregrounds.main|||
size.unit_byte|foregrounds.subdued|||
size.unit_kilo|foregrounds.subdued|||
size.unit_mega|foregrounds.subdued|||
size.unit_giga|foregrounds.subdued|||
size.unit_huge|foregrounds.subdued|||
users.user_you|semantic.success|||
users.user_root|semantic.error|||
users.user_other|foregrounds.dim|||
users.group_yours|semantic.success|||
users.group_other|foregrounds.dim|||
users.group_root|semantic.error|||
links.normal|foregrounds.dim|||
links.multi_link_file|semantic.warning|||
git.new|git.added|||
git.modified|git.changed|||
git.deleted|git.deleted|||
git.renamed|semantic.keyword|||
git.typechange|semantic.keyword|||
git.ignored|foregrounds.subdued|||
git.conflicted|semantic.error|||
git_repo.branch_main|foregrounds.heading|||
git_repo.branch_other|semantic.keyword|||
git_repo.git_clean|semantic.success|||
git_repo.git_dirty|semantic.warning|||
security_context.none|foregrounds.subdued|||
security_context.selinux.colon|foregrounds.subdued|||
security_context.selinux.user|foregrounds.subdued|||
security_context.selinux.role|foregrounds.subdued|||
security_context.selinux.typ|foregrounds.subdued|||
security_context.selinux.range|foregrounds.subdued|||
file_type.image|purples.lavender|||png,jpg,svg
file_type.video|purples.muted_purple|||mp4,mkv
file_type.music|purples.bright_purple|||mp3,ogg
file_type.lossless|purples.bright_purple|||flac,wav
file_type.crypto|ansi.bright_yellow|||age,pem
file_type.document|blues_slates.cloud_slate|||pdf,key
file_type.compressed|ansi.bright_red|||zip,gz,tar,tar.gz
file_type.temp|foregrounds.subdued|||tmp,bak
file_type.compiled|foregrounds.dim|||so,o
file_type.build|teals.mid_bright|||ninja
file_type.source|semantic.type|||go,rs,py,ts,lua,js
punctuation|semantic.punctuation|||
date|foregrounds.dim|||
inode|foregrounds.subdued|||
blocks|foregrounds.subdued|||
header|foregrounds.heading|bold||
octal|foregrounds.subdued|||
flags|foregrounds.subdued|||
symlink_path|foregrounds.dim|||
control_char|semantic.error|||
broken_symlink|semantic.error||or|
broken_path_overlay|semantic.error|||
`

// These templates vendor markdown-preview.nvim's CSS at
// a923f5fc5ba36a3b17e289dc35dc17f66d0548ee. Keep every upstream selector and
// non-color declaration; only color values and the approved heading/page colors
// differ. validateMarkdownPreviewVendorCommit forces an explicit rebase when
// the plugin lock changes.
const markdownPreviewMarkdownTemplate = `/*
 * github like style
 * https://github.com/iamcco/markdown.css/blob/master/dest/github/markdown.css
 */
:root {
    --color-text-primary: {{foregrounds.main}};
    --color-text-tertiary: {{foregrounds.dim}};
    --color-text-link: {{teals.bright}};
    --color-bg-primary: {{core.background}};
    --color-bg-secondary: {{core.ui_shadow}};
    --color-bg-tertiary: {{core.panel_bg}};
    --color-border-primary: {{teals.border}};
    --color-border-secondary: {{core.panel_bg}};
    --color-border-tertiary: {{core.ui_shadow}};
    --color-kbd-foreground: {{foregrounds.dim}};
    --color-markdown-blockquote-border: {{teals.border}};
    --color-markdown-table-border: {{teals.border}};
    --color-markdown-table-tr-border: {{core.ui_shadow}};
    --color-markdown-code-bg: {{core.panel_bg}};
}
[data-theme="dark"] {
    --color-text-primary: {{foregrounds.main}};
    --color-text-tertiary: {{foregrounds.dim}};
    --color-text-link: {{teals.bright}};
    --color-bg-primary: {{core.background}};
    --color-bg-secondary: {{core.ui_shadow}};
    --color-bg-tertiary: {{core.panel_bg}};
    --color-border-primary: {{teals.border}};
    --color-border-secondary: {{core.panel_bg}};
    --color-border-tertiary: {{core.ui_shadow}};
    --color-kbd-foreground: {{foregrounds.dim}};
    --color-markdown-blockquote-border: {{teals.border}};
    --color-markdown-table-border: {{teals.border}};
    --color-markdown-table-tr-border: {{core.ui_shadow}};
    --color-markdown-code-bg: {{core.panel_bg}};
    --foreground-color: {{foregrounds.main}};
    --background-color: {{core.background}};
    --secondary-background-color: {{core.darkest_bg}};
    --border-color: {{teals.border}};
}
.markdown-body ol ol,
.markdown-body ul ol,
.markdown-body ol ul,
.markdown-body ul ul,
.markdown-body ol ul ol,
.markdown-body ul ul ol,
.markdown-body ol ul ul,
.markdown-body ul ul ul {
  margin-top: 0;
  margin-bottom: 0;
}
.markdown-body {
  font-family: "Helvetica Neue", Helvetica, "Segoe UI", Arial, freesans, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";
  font-size: 16px;
  color: var(--color-text-primary);
  line-height: 1.6;
  word-wrap: break-word;
  padding: 45px;
  background: var(--color-bg-primary);
  border: 1px solid var(--color-border-primary);
  -webkit-border-radius: 0 0 3px 3px;
  border-radius: 0 0 3px 3px;
}
.markdown-body > *:first-child {
  margin-top: 0 !important;
}
.markdown-body > *:last-child {
  margin-bottom: 0 !important;
}
.markdown-body .table-of-contents ol {
  list-style: none;
}
.markdown-body .table-of-contents > ol {
  padding-left: 0;
}
.markdown-body * {
  -webkit-box-sizing: border-box;
  -moz-box-sizing: border-box;
  box-sizing: border-box;
}
.markdown-body h1,
.markdown-body h2,
.markdown-body h3,
.markdown-body h4,
.markdown-body h5,
.markdown-body h6 {
  margin-top: 1em;
  margin-bottom: 16px;
  font-weight: bold;
  line-height: 1.4;
}
.markdown-body h1 .anchor,
.markdown-body h2 .anchor,
.markdown-body h3 .anchor,
.markdown-body h4 .anchor,
.markdown-body h5 .anchor,
.markdown-body h6 .anchor {
  margin-left: -24px;
  visibility: hidden;
}
.markdown-body h1:hover .anchor,
.markdown-body h2:hover .anchor,
.markdown-body h3:hover .anchor,
.markdown-body h4:hover .anchor,
.markdown-body h5:hover .anchor,
.markdown-body h6:hover .anchor {
  visibility: visible;
}
.markdown-body p,
.markdown-body blockquote,
.markdown-body ul,
.markdown-body ol,
.markdown-body dl,
.markdown-body table,
.markdown-body pre {
  margin-top: 0;
  margin-bottom: 16px;
}
.markdown-body h1 {
  margin: 0.67em 0;
  padding-bottom: 0.3em;
  font-size: 2.25em;
  line-height: 1.2;
  color: {{foregrounds.heading}};
  border-bottom: 1px solid var(--color-border-secondary);
}
.markdown-body h2 {
  padding-bottom: 0.3em;
  font-size: 1.75em;
  line-height: 1.225;
  color: {{teals.bright}};
  border-bottom: 1px solid var(--color-border-secondary);
}
.markdown-body h3 {
  font-size: 1.5em;
  line-height: 1.43;
  color: {{teals.mid_bright}};
}
.markdown-body h4 {
  font-size: 1.25em;
  color: {{foregrounds.main}};
}
.markdown-body h5 {
  font-size: 1em;
  color: {{blues_slates.cloud_slate}};
}
.markdown-body h6 {
  font-size: 1em;
  color: {{foregrounds.subdued}};
}
.markdown-body hr {
  margin-top: 20px;
  margin-bottom: 20px;
  height: 0;
  border: 0;
  border-top: 1px solid var(--color-border-primary);
}
.markdown-body ol,
.markdown-body ul {
  padding-left: 2em;
}
.markdown-body ol ol,
.markdown-body ul ol {
  list-style-type: lower-roman;
}
.markdown-body ol ul,
.markdown-body ul ul {
  list-style-type: circle;
}
.markdown-body ol ul ul,
.markdown-body ul ul ul {
  list-style-type: square;
}
.markdown-body ol {
  list-style-type: decimal;
}
.markdown-body ul {
  list-style-type: disc;
}
.markdown-body dl {
  margin-bottom: 1.3em
}
.markdown-body dl dt {
  font-weight: 700;
}
.markdown-body dl dd {
  margin-left: 0;
}
.markdown-body dl dd p {
  margin-bottom: 0.8em;
}
.markdown-body blockquote {
  margin-left: 0;
  margin-right: 0;
  padding: 0 15px;
  color: var(--color-text-tertiary);
  border-left: 4px solid var(--color-markdown-blockquote-border);
}
.markdown-body table {
  display: block;
  width: 100%;
  overflow: auto;
  word-break: normal;
  word-break: keep-all;
  border-collapse: collapse;
  border-spacing: 0;
}
.markdown-body table tr {
  background-color: var(--color-bg-primary);
  border-top: 1px solid var(--color-markdown-table-tr-border);
}
.markdown-body table tr:nth-child(2n) {
  background-color: var(--color-bg-tertiary);
}
.markdown-body table th,
.markdown-body table td {
  padding: 6px 13px;
  border: 1px solid var(--color-markdown-table-border);
  vertical-align: top;
}
.markdown-body kbd {
  display: inline-block;
  padding: 5px 6px;
  font: 14px SFMono-Regular,Consolas,Liberation Mono,Menlo,monospace;
  line-height: 10px;
  color: var(--color-kbd-foreground);
  vertical-align: middle;
  background-color: var(--color-bg-secondary);
  border: 1px solid var(--color-border-tertiary);
  border-radius: 3px;
  box-shadow: inset 0 -1px 0 var(--color-border-tertiary);
}
.markdown-body pre {
  word-wrap: normal;
  padding: 16px;
  overflow: auto;
  font-size: 85%;
  line-height: 1.45;
  background-color: var(--color-bg-tertiary);
  -webkit-border-radius: 3px;
  border-radius: 3px;
}
.markdown-body pre code {
  display: inline;
  max-width: initial;
  padding: 0;
  margin: 0;
  overflow: initial;
  font-size: 100%;
  line-height: inherit;
  word-wrap: normal;
  white-space: pre;
  border: 0;
  -webkit-border-radius: 3px;
  border-radius: 3px;
  background-color: transparent;
}
.markdown-body pre code:before,
.markdown-body pre code:after {
  content: normal;
}
.markdown-body code {
  font-family: Consolas, "Liberation Mono", Menlo, Courier, monospace;
  padding: 0;
  padding-top: 0.2em;
  padding-bottom: 0.2em;
  margin: 0;
  font-size: 85%;
  background-color: var(--color-markdown-code-bg);
  -webkit-border-radius: 3px;
  border-radius: 3px;
}
.markdown-body code:before,
.markdown-body code:after {
  letter-spacing: -0.2em;
  content: "\00a0";
}
.markdown-body a {
  color: var(--color-text-link);
  text-decoration: none;
  background: transparent;
}
.markdown-body img {
  max-width: 100%;
  max-height: 100%;
}
.markdown-body strong {
  font-weight: bold;
}
.markdown-body em {
  font-style: italic;
}
.markdown-body del {
  text-decoration: line-through;
}
.task-list-item {
  list-style-type: none;
}
.task-list-item input {
  font: 13px/1.4 Helvetica, arial, nimbussansl, liberationsans, freesans, clean, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";
  margin: 0 0.35em 0.25em -1.6em;
  vertical-align: middle;
}
.task-list-item input[disabled] {
  cursor: default;
}
.task-list-item input[type="checkbox"] {
  -webkit-box-sizing: border-box;
  -moz-box-sizing: border-box;
  box-sizing: border-box;
  padding: 0;
}
.task-list-item input[type="radio"] {
  -webkit-box-sizing: border-box;
  -moz-box-sizing: border-box;
  box-sizing: border-box;
  padding: 0;
}
`

const markdownPreviewHighlightTemplate = `/*

github.com style (c) Vasily Polovnyov <vast@whiteants.net>

*/
:root {
    --color-text-primary: {{foregrounds.main}};
}
[data-theme="dark"] {
    --color-text-primary: {{foregrounds.main}};
}

.hljs {
  display: block;
  overflow-x: auto;
  padding: 0.5em;
  color: var(--color-text-primary);
  background: {{core.panel_bg}};
}

.hljs-comment,
.hljs-quote {
  color: {{semantic.comment}};
  font-style: italic;
}

.hljs-keyword,
.hljs-selector-tag,
.hljs-subst {
  color: {{semantic.keyword}};
  font-weight: bold;
}
.hljs-number,
.hljs-literal {
  color: {{semantic.number}};
}
.hljs-variable,
.hljs-template-variable,
.hljs-tag .hljs-attr {
  color: {{semantic.variable}};
}

.hljs-string,
.hljs-doctag {
  color: {{semantic.string}};
}

.hljs-title,
.hljs-section,
.hljs-selector-id {
  color: {{semantic.function}};
  font-weight: bold;
}

.hljs-subst {
  font-weight: normal;
}

.hljs-type,
.hljs-class .hljs-title {
  color: {{semantic.type}};
  font-weight: bold;
}

.hljs-tag,
.hljs-name,
.hljs-attribute {
  color: {{foregrounds.heading}};
  font-weight: normal;
}

.hljs-regexp,
.hljs-link {
  color: {{teals.bright}};
}
.hljs-symbol,
.hljs-bullet {
  color: {{semantic.punctuation}};
}

.hljs-built_in,
.hljs-builtin-name {
  color: {{teals.mid_bright}};
}

.hljs-meta {
  color: {{foregrounds.dim}};
  font-weight: bold;
}

.hljs-deletion {
  background: {{nvim.diff_delete_bg}};
}

.hljs-addition {
  background: {{nvim.diff_add_bg}};
}

.hljs-emphasis {
  font-style: italic;
}

.hljs-strong {
  font-weight: bold;
}
`

const lazygitTemplate = `    # BEGIN GENERATED COLORS
    # ボーダー色
    activeBorderColor:
      - '{{teals.bright}}' # Vibrant Teal
      - bold
    inactiveBorderColor:
      - '{{teals.border}}' # UI Border (Visibility improved)
    # テキスト色
    optionsTextColor:
      - '{{foregrounds.main}}'
    defaultFgColor:
      - '{{foregrounds.main}}'
    # 選択行の背景 (Ocean Blue - 視認性と可読性のバランス)
    selectedLineBgColor:
      - '{{blues_slates.ocean_blue}}'
    selectedRangeBgColor:
      - '{{blues_slates.ocean_blue}}'
    # Git関連の色
    unstagedChangesColor:
      - '{{git.changed}}' # Git changed
    cherryPickedCommitFgColor:
      - '{{teals.bright}}'
    cherryPickedCommitBgColor:
      - '{{core.panel_bg}}' # Dark Teal Panel
  # 著者色設定
  authorColors:
    '*': '{{blues_slates.git_blame_gray}}' # Git Blame Gray (improved visibility)
    # END GENERATED COLORS
`

const ghDashTemplate = `        # BEGIN GENERATED COLORS
        text:
            primary: "{{foregrounds.main}}"
            secondary: "{{foregrounds.dim}}"
            inverted: "{{core.darkest_bg}}"
            faint: "{{foregrounds.subdued}}"
            warning: "{{semantic.warning}}"
            success: "{{semantic.success}}"
            error: "{{semantic.error}}"
            actor: "{{foregrounds.heading}}"
        background:
            selected: "{{core.active_line}}"
        border:
            primary: "{{teals.border}}"
            secondary: "{{teals.border}}"
            faint: "{{core.ui_shadow}}"
        icon:
            newcontributor: "{{semantic.success}}"
            contributor: "{{foregrounds.heading}}"
            collaborator: "{{semantic.warning}}"
            member: "{{semantic.warning}}"
            owner: "{{semantic.warning}}"
        # END GENERATED COLORS
`

const herdrTemplate = `# BEGIN GENERATED COLORS
accent = "{{ansi.blue}}"
panel_bg = "reset"
surface0 = "reset"
surface1 = "{{core.active_line}}"
surface_dim = "{{ansi.bright_black}}"
overlay0 = "{{foregrounds.dim}}"
overlay1 = "{{ansi.bright_white}}"
text = "{{foregrounds.main}}"
subtext0 = "{{foregrounds.dim}}"
mauve = "{{foregrounds.heading}}"
green = "{{ansi.green}}"
yellow = "{{ansi.yellow}}"
red = "{{ansi.bright_red}}"
blue = "{{ansi.blue}}"
teal = "{{ansi.cyan}}"
peach = "{{semantic.warning}}" # herdr 0.7.4では未使用
# END GENERATED COLORS
`

const batThemeTemplate = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>name</key>
  <string>ghost-visor</string>
  <key>settings</key>
  <array>
    <dict>
      <key>settings</key>
      <dict>
        <key>background</key>
        <string>{{core.background}}</string>
        <key>foreground</key>
        <string>{{foregrounds.main}}</string>
        <key>lineHighlight</key>
        <string>{{core.active_line}}</string>
        <key>gutterForeground</key>
        <string>{{foregrounds.dim}}</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Comment</string>
      <key>scope</key>
      <string>comment</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>{{semantic.comment}}</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>String</string>
      <key>scope</key>
      <string>string</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>{{semantic.string}}</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Numeric Constant</string>
      <key>scope</key>
      <string>constant.numeric</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>{{semantic.number}}</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Language Constant</string>
      <key>scope</key>
      <string>constant.language</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>{{semantic.constant}}</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Character Escape</string>
      <key>scope</key>
      <string>constant.character.escape</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>{{foregrounds.bright}}</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Keyword</string>
      <key>scope</key>
      <string>keyword</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>{{semantic.keyword}}</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Operator</string>
      <key>scope</key>
      <string>keyword.operator</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>{{semantic.operator}}</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Import Keyword</string>
      <key>scope</key>
      <string>keyword.control.import</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>{{teals.bright}}</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Storage Type</string>
      <key>scope</key>
      <string>storage.type</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>{{semantic.type}}</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Storage Modifier</string>
      <key>scope</key>
      <string>storage.modifier</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>{{semantic.keyword}}</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Function Declaration</string>
      <key>scope</key>
      <string>entity.name.function</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>{{semantic.function}}</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Function Call</string>
      <key>scope</key>
      <string>variable.function</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>{{semantic.function}}</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Support Function</string>
      <key>scope</key>
      <string>support.function</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>{{semantic.function}}</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Class Name</string>
      <key>scope</key>
      <string>entity.name.class</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>{{semantic.type}}</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Type Name</string>
      <key>scope</key>
      <string>entity.name.type</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>{{semantic.type}}</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Support Type</string>
      <key>scope</key>
      <string>support.type</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>{{semantic.type}}</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Tag Name</string>
      <key>scope</key>
      <string>entity.name.tag</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>{{teals.bright}}</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Attribute Name</string>
      <key>scope</key>
      <string>entity.other.attribute-name</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>{{foregrounds.heading}}</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Parameter</string>
      <key>scope</key>
      <string>variable.parameter</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>{{semantic.variable}}</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Language Variable</string>
      <key>scope</key>
      <string>variable.language</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>{{semantic.builtin_variable}}</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Separator Punctuation</string>
      <key>scope</key>
      <string>punctuation.separator</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>{{semantic.punctuation}}</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Terminator Punctuation</string>
      <key>scope</key>
      <string>punctuation.terminator</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>{{semantic.punctuation}}</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Section Punctuation</string>
      <key>scope</key>
      <string>punctuation.section</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>{{semantic.punctuation}}</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Definition Punctuation</string>
      <key>scope</key>
      <string>punctuation.definition</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>{{semantic.punctuation}}</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Accessor Punctuation</string>
      <key>scope</key>
      <string>punctuation.accessor</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>{{semantic.punctuation}}</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Invalid</string>
      <key>scope</key>
      <string>invalid.illegal</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>{{semantic.error}}</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>YAML Key</string>
      <key>scope</key>
      <string>entity.name.tag.yaml</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>{{teals.bright}}</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>YAML Boolean</string>
      <key>scope</key>
      <string>constant.language.boolean.yaml</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>{{semantic.keyword}}</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>YAML Null</string>
      <key>scope</key>
      <string>constant.language.null.yaml</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>{{semantic.keyword}}</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>YAML Number</string>
      <key>scope</key>
      <string>source.yaml constant.numeric</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>{{purples.lavender}}</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>YAML List Marker</string>
      <key>scope</key>
      <string>punctuation.definition.block.sequence.item.yaml</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>{{semantic.punctuation}}</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Markdown Heading</string>
      <key>scope</key>
      <string>markup.heading</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>{{foregrounds.heading}}</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Markdown Bold</string>
      <key>scope</key>
      <string>markup.bold</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>{{ansi.bright_white}}</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Markdown Italic</string>
      <key>scope</key>
      <string>markup.italic</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>{{foregrounds.bright}}</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Markdown Raw</string>
      <key>scope</key>
      <string>markup.raw</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>{{semantic.string}}</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Markdown Quote</string>
      <key>scope</key>
      <string>markup.quote</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>{{foregrounds.dim}}</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Markdown List</string>
      <key>scope</key>
      <string>markup.list</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>{{semantic.punctuation}}</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Markdown Link</string>
      <key>scope</key>
      <string>markup.underline.link</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>{{teals.bright}}</string>
      </dict>
    </dict>
  </array>
</dict>
</plist>
`

const vimTemplate = `" BEGIN GENERATED COLORS
" {{metadata.name}} カラースキーム（TOML準拠）
" ========================================

" 背景・前景（透過）
highlight Normal guibg=NONE guifg={{foregrounds.main}} ctermbg=NONE ctermfg={{xterm:foregrounds.main}}
highlight NormalNC guibg=NONE guifg={{foregrounds.main}} ctermbg=NONE ctermfg={{xterm:foregrounds.main}}
highlight NonText guibg=NONE guifg={{teals.border}} ctermbg=NONE ctermfg={{xterm:teals.border}}
highlight EndOfBuffer guibg=NONE ctermbg=NONE

" 行番号
highlight LineNr guifg={{blues_slates.comment_gray}} guibg=NONE ctermfg={{xterm:blues_slates.comment_gray}} ctermbg=NONE
highlight CursorLineNr guifg={{ansi.bright_white}} guibg=NONE ctermfg={{xterm:ansi.bright_white}} ctermbg=NONE gui=bold cterm=bold

" カーソルライン
highlight CursorLine guibg={{core.ui_shadow}} ctermbg={{xterm:core.ui_shadow}} cterm=NONE gui=NONE
highlight CursorColumn guibg={{core.ui_shadow}} ctermbg={{xterm:core.ui_shadow}}
highlight ColorColumn guibg={{core.ui_shadow}} ctermbg={{xterm:core.ui_shadow}}

" 構文ハイライト
highlight Comment guifg={{semantic.comment}} ctermfg={{xterm:semantic.comment}}
highlight Keyword guifg={{semantic.keyword}} ctermfg={{xterm:semantic.keyword}}
highlight Statement guifg={{semantic.keyword}} ctermfg={{xterm:semantic.keyword}}
highlight Conditional guifg={{semantic.keyword}} ctermfg={{xterm:semantic.keyword}}
highlight Repeat guifg={{semantic.keyword}} ctermfg={{xterm:semantic.keyword}}
highlight String guifg={{semantic.string}} ctermfg={{xterm:semantic.string}}
highlight Character guifg={{semantic.string}} ctermfg={{xterm:semantic.string}}
highlight Function guifg={{semantic.function}} ctermfg={{xterm:semantic.function}}
highlight Identifier guifg={{semantic.variable}} ctermfg={{xterm:semantic.variable}}
highlight Number guifg={{semantic.number}} ctermfg={{xterm:semantic.number}}
highlight Float guifg={{semantic.number}} ctermfg={{xterm:semantic.number}}
highlight Boolean guifg={{semantic.number}} ctermfg={{xterm:semantic.number}}
highlight Type guifg={{semantic.type}} ctermfg={{xterm:semantic.type}}
highlight Constant guifg={{semantic.constant}} ctermfg={{xterm:semantic.constant}}
highlight Operator guifg={{semantic.operator}} ctermfg={{xterm:semantic.operator}}
highlight PreProc guifg={{semantic.function}} ctermfg={{xterm:semantic.function}}
highlight Special guifg={{blues_slates.slate_mid}} ctermfg={{xterm:blues_slates.slate_mid}}
highlight Todo guifg={{semantic.function}} guibg=NONE ctermfg={{xterm:semantic.function}} ctermbg=NONE gui=bold cterm=bold

" Markdownのバッククォート（インラインコード ` + "`code`" + ` / コードフェンス ` + "```" + `）
" 既定では markdownCodeDelimiter→Delimiter→Special({{blues_slates.slate_mid}}) で暗く沈むため、
" Special自体(Conceal用途)は変えずデリミタだけ視認可能なTeal(Operator色)に上書き
highlight markdownCodeDelimiter guifg={{semantic.operator}} ctermfg={{xterm:semantic.operator}}
" 見出しの # も同根（markdownHeadingDelimiter→Delimiter→Special）で沈むため同様に上書き
highlight markdownHeadingDelimiter guifg={{semantic.operator}} ctermfg={{xterm:semantic.operator}}
highlight Underlined guifg={{semantic.function}} ctermfg={{xterm:semantic.function}} gui=underline cterm=underline
highlight Conceal guifg={{blues_slates.slate_mid}} ctermfg={{xterm:blues_slates.slate_mid}}

" UI要素
highlight SignColumn guibg=NONE ctermbg=NONE
highlight FoldColumn guibg=NONE guifg={{teals.border}} ctermbg=NONE ctermfg={{xterm:teals.border}}
highlight VertSplit guifg={{teals.border}} guibg=NONE ctermfg={{xterm:teals.border}} ctermbg=NONE
highlight StatusLine guifg={{foregrounds.main}} guibg=NONE ctermfg={{xterm:foregrounds.main}} ctermbg=NONE gui=bold cterm=bold
highlight StatusLineNC guifg={{foregrounds.subdued}} guibg=NONE ctermfg={{xterm:foregrounds.subdued}} ctermbg=NONE gui=NONE cterm=NONE
highlight TabLine guifg={{foregrounds.subdued}} guibg=NONE ctermfg={{xterm:foregrounds.subdued}} ctermbg=NONE
highlight TabLineSel guifg={{foregrounds.main}} guibg=NONE ctermfg={{xterm:foregrounds.main}} ctermbg=NONE gui=bold cterm=bold
highlight TabLineFill guibg=NONE ctermbg=NONE
highlight Visual guibg={{core.selection_bg}} guifg={{core.selection_fg}} ctermbg={{xterm:core.selection_bg}} ctermfg={{xterm:core.selection_fg}}
highlight Pmenu guibg={{core.ui_shadow}} guifg={{foregrounds.main}} ctermbg={{xterm:core.ui_shadow}} ctermfg={{xterm:foregrounds.main}}
highlight PmenuSel guibg={{core.ui_shadow}} guifg={{ansi.bright_white}} ctermbg={{xterm:core.ui_shadow}} ctermfg={{xterm:ansi.bright_white}}
highlight Search guibg={{core.ui_shadow}} guifg={{semantic.function}} ctermbg={{xterm:core.ui_shadow}} ctermfg={{xterm:semantic.function}}
highlight IncSearch guibg={{semantic.function}} guifg={{core.selection_fg}} ctermbg={{xterm:semantic.function}} ctermfg={{xterm:core.selection_fg}}
highlight MatchParen guibg={{teals.border}} guifg={{ansi.bright_white}} ctermbg={{xterm:teals.border}} ctermfg={{xterm:ansi.bright_white}} gui=bold cterm=bold

" 追加グループ
highlight Directory guifg={{semantic.function}} ctermfg={{xterm:semantic.function}}
highlight Title guifg={{foregrounds.heading}} ctermfg={{xterm:foregrounds.heading}} gui=bold cterm=bold
highlight Folded guibg={{core.ui_shadow}} guifg={{foregrounds.subdued}} ctermbg={{xterm:core.ui_shadow}} ctermfg={{xterm:foregrounds.subdued}}
highlight WildMenu guibg={{core.ui_shadow}} guifg={{ansi.bright_white}} ctermbg={{xterm:core.ui_shadow}} ctermfg={{xterm:ansi.bright_white}}
highlight Question guifg={{semantic.function}} ctermfg={{xterm:semantic.function}}
highlight MoreMsg guifg={{semantic.function}} ctermfg={{xterm:semantic.function}}
highlight ModeMsg guifg={{foregrounds.main}} ctermfg={{xterm:foregrounds.main}} gui=bold cterm=bold
highlight QuickFixLine guibg={{core.ui_shadow}} ctermbg={{xterm:core.ui_shadow}}
highlight ErrorMsg guifg={{semantic.error}} ctermfg={{xterm:semantic.error}}
highlight WarningMsg guifg={{semantic.warning}} ctermfg={{xterm:semantic.warning}}

" Diff
highlight DiffAdd guifg={{git.added}} guibg={{nvim.diff_add_bg}} ctermfg={{xterm:git.added}} ctermbg={{xterm:nvim.diff_add_bg}}
highlight DiffChange guifg={{git.changed}} guibg={{nvim.diff_change_bg}} ctermfg={{xterm:git.changed}} ctermbg={{xterm:nvim.diff_change_bg}}
highlight DiffDelete guifg={{git.deleted}} guibg={{nvim.diff_delete_bg}} ctermfg={{xterm:git.deleted}} ctermbg={{xterm:nvim.diff_delete_bg}}
highlight DiffText guifg={{foregrounds.heading}} guibg=NONE ctermfg={{xterm:foregrounds.heading}} ctermbg=NONE gui=bold cterm=bold

" スペルチェック
highlight SpellBad guifg={{semantic.error}} ctermfg={{xterm:semantic.error}} gui=undercurl cterm=underline
highlight SpellCap guifg={{semantic.warning}} ctermfg={{xterm:semantic.warning}} gui=undercurl cterm=underline
" END GENERATED COLORS
`

const statuslineANSITemplate = `# BEGIN GENERATED COLORS: ANSI
# セクション本体テキスト用前景色
C_MODEL="\e[38;2;{{rgb:foregrounds.main}}m"   # {{foregrounds.main}} foregrounds.main
C_DIR="\e[38;2;{{rgb:foregrounds.heading}}m"     # {{foregrounds.heading}} foregrounds.heading
C_GIT="\e[38;2;{{rgb:teals.bright}}m"     # {{teals.bright}} teals.bright
C_BUSY="\e[38;2;{{rgb:purples.bright_purple}}m"    # {{lower:purples.bright_purple}} purples.bright_purple

# 使用率の色（閾値で変化）
pct=${USED_PCT%.*}
pct=${pct:-0}
if [ "$pct" -gt 75 ]; then
  C_PCT="\e[38;2;{{rgb:purples.bright_purple}}m"   # {{lower:purples.bright_purple}}
elif [ "$pct" -gt 50 ]; then
  C_PCT="\e[38;2;{{rgb:purples.lavender}}m"   # {{purples.lavender}}
else
  C_PCT="\e[38;2;{{rgb:teals.mid_bright}}m"    # {{teals.mid_bright}} 安全（暗いtealは帯背景に沈む）
fi

# 5時間リミット使用率とバー
rate_used_int=""
if [[ "$RATE_USED" =~ ^[0-9]+([.][0-9]+)?$ ]]; then
  rate_used_int=$((10#${RATE_USED%%.*}))
  [ "$rate_used_int" -gt 100 ] && rate_used_int=100

  if [ "$rate_used_int" -gt 75 ]; then
    C_RATE="\e[38;2;{{rgb:purples.bright_purple}}m"   # {{lower:purples.bright_purple}} critical
  elif [ "$rate_used_int" -gt 50 ]; then
    C_RATE="\e[38;2;{{rgb:purples.lavender}}m"   # {{purples.lavender}} warning
  else
    C_RATE="\e[38;2;{{rgb:teals.mid_bright}}m"    # {{teals.mid_bright}} safe
  fi
  C_RATETRACK="\e[38;2;{{rgb:core.panel_bg}}m"   # {{core.panel_bg}} track

  build_meter "$rate_used_int" 8
  rate_bar_filled=$METER_FILLED
  rate_bar_track=$METER_TRACK

  format_remaining "$RATE_RESET"
  rate_remaining=$FORMATTED_REMAINING
fi

# 週次リミット使用率とバー
week_used_int=""
if [[ "$WEEK_USED" =~ ^[0-9]+([.][0-9]+)?$ ]]; then
  week_used_int=$((10#${WEEK_USED%%.*}))
  [ "$week_used_int" -gt 100 ] && week_used_int=100

  if [ "$week_used_int" -gt 75 ]; then
    C_WEEK="\e[38;2;{{rgb:purples.bright_purple}}m"   # {{lower:purples.bright_purple}} critical
  elif [ "$week_used_int" -gt 50 ]; then
    C_WEEK="\e[38;2;{{rgb:purples.lavender}}m"   # {{purples.lavender}} warning
  else
    C_WEEK="\e[38;2;{{rgb:teals.mid_bright}}m"    # {{teals.mid_bright}} safe
  fi
  C_WEEKTRACK="\e[38;2;{{rgb:core.panel_bg}}m"   # {{core.panel_bg}} track

  build_meter "$week_used_int" 8
  week_bar_filled=$METER_FILLED
  week_bar_track=$METER_TRACK

  format_remaining "$WEEK_RESET"
  week_remaining=$FORMATTED_REMAINING
fi

# END GENERATED COLORS: ANSI
`

const statuslineSegmentsTemplate = `# BEGIN GENERATED COLORS: SEGMENTS
# --- 1段目: モデル / コンテキスト使用率 / ディレクトリ / Gitブランチ ---
row1=()
row1+=("{{core.darkest_bg}}|${C_MODEL}${MODEL}")
row1+=("{{nvim.gutter_bg}}|${C_PCT}󰍛 ${pct}%")
row1+=("{{core.background}}|${C_DIR}${DIR_NAME}")
[ -n "$GIT_BRANCH" ] && row1+=("{{core.darkest_bg}}|${C_GIT}${GIT_BRANCH}")

# --- 2段目: busyマーカー / 5時間リミット / 週次リミット ---
row2=()
# herdrが画面下の非空3行だけを走査するため、busyマーカーを下段先頭に置く
[ "$CODEX_BUSY" = "1" ] && row2+=("{{core.darkest_bg}}|${C_BUSY}󰚩")
[ "$BG_BUSY" = "1" ] && row2+=("{{nvim.gutter_bg}}|${C_BUSY}󰜎")
if [ -n "$rate_used_int" ]; then
  row2+=("{{core.background}}|${C_RATE}5h ${rate_bar_filled}${C_RATETRACK}${rate_bar_track}${C_RATE} ${rate_used_int}%${rate_remaining:+ ${rate_remaining}}")
fi
if [ -n "$week_used_int" ]; then
  row2+=("{{core.darkest_bg}}|${C_WEEK}Week ${week_bar_filled}${C_WEEKTRACK}${week_bar_track}${C_WEEK} ${week_used_int}%${week_remaining:+ ${week_remaining}}")
fi

# END GENERATED COLORS: SEGMENTS
`

const colorSystemANSITemplate = `<!-- BEGIN GENERATED COLORS -->
` + "```" + `
 0: {{ansi.black}} (Black)           8: {{ansi.bright_black}} (Bright Black)
 1: {{ansi.red}} (Red)             9: {{ansi.bright_red}} (Bright Red)
 2: {{ansi.green}} (Green)          10: {{ansi.bright_green}} (Bright Green)
 3: {{ansi.yellow}} (Yellow)         11: {{ansi.bright_yellow}} (Bright Yellow)
 4: {{ansi.blue}} (Blue)           12: {{ansi.bright_blue}} (Bright Blue)
 5: {{ansi.magenta}} (Magenta)        13: {{ansi.bright_magenta}} (Bright Magenta)
 6: {{ansi.cyan}} (Cyan)           14: {{ansi.bright_cyan}} (Bright Cyan)
 7: {{ansi.white}} (White)          15: {{ansi.bright_white}} (Bright White)
` + "```" + `
<!-- END GENERATED COLORS -->

`
