package sourceinventory

import (
	"bytes"
	"fmt"
	"go/format"
)

func Render(result Result) ([]byte, error) {
	var buffer bytes.Buffer
	buffer.WriteString("// Code generated by cmd/generate-color-inventory; DO NOT EDIT.\n\n")
	buffer.WriteString("package verifycolors\n\n")
	buffer.WriteString("// BEGIN GENERATED COLOR INVENTORY\n")
	buffer.WriteString("var generatedPairs = []PairSpec{\n")
	for _, pair := range result.Pairs {
		fmt.Fprintf(&buffer, "\t{\n")
		fmt.Fprintf(&buffer, "\t\tConsumerID: %q,\n", pair.ConsumerID)
		fmt.Fprintf(&buffer, "\t\tForeground: %q,\n", pair.Foreground)
		if pair.Background.Ambient {
			buffer.WriteString("\t\tBackground: AmbientBackground(),\n")
		} else {
			fmt.Fprintf(&buffer, "\t\tBackground: TokenBackground(%q),\n", pair.Background.Token)
		}
		fmt.Fprintf(&buffer, "\t\tClass: %q,\n", pair.Class)
		buffer.WriteString("\t\tProfiles: []RenderProfile{")
		for index, profile := range pair.Profiles {
			if index > 0 {
				buffer.WriteString(", ")
			}
			fmt.Fprintf(&buffer, "%q", profile)
		}
		buffer.WriteString("},\n")
		fmt.Fprintf(&buffer, "\t\tRole: %q,\n", pair.Role)
		if pair.Reason != "" {
			fmt.Fprintf(&buffer, "\t\tReason: %q,\n", pair.Reason)
		}
		fmt.Fprintf(&buffer, "\t\tSource: %q,\n", pair.Source)
		buffer.WriteString("\t},\n")
	}
	buffer.WriteString("}\n\n")
	buffer.WriteString("var generatedCoverageNotes = []CoverageNote{\n")
	for _, note := range result.CoverageNotes {
		fmt.Fprintf(&buffer, "\t{ID: %q, Reason: %q, Source: %q},\n", note.ID, note.Reason, note.Source)
	}
	buffer.WriteString("}\n")
	buffer.WriteString("// END GENERATED COLOR INVENTORY\n")

	formatted, err := format.Source(buffer.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated inventory: %w", err)
	}
	return formatted, nil
}
