return {
  {
    "akinsho/bufferline.nvim",
    keys = {
      { "<leader>bP", false },
      { "<leader>bj", false },
      { "<leader>bl", false },
      { "<leader>bp", false },
      { "<leader>br", false },
      { "[B", false },
      { "[b", false },
      { "]B", false },
      { "]b", false },
    },
  },
  {
    "stevearc/conform.nvim",
    keys = {
      { "<leader>cF", false, mode = { "n", "x" } },
    },
  },
  {
    "mason-org/mason.nvim",
    keys = {
      { "<leader>cm", false },
    },
  },
  {
    "folke/noice.nvim",
    keys = {
      { "<S-Enter>", false, mode = { "c" } },
      { "<c-b>", false, mode = { "i", "s" } },
      { "<c-f>", false, mode = { "i", "n", "s" } },
      { "<leader>sn", false },
      { "<leader>sna", false },
      { "<leader>snd", false },
      { "<leader>snh", false },
      { "<leader>snl", false },
      { "<leader>snt", false },
    },
  },
  {
    "folke/snacks.nvim",
    keys = {
      { "<leader>,", false },
      { "<leader>.", false },
      { "<leader>/", false },
      { "<leader>E", false },
      { "<leader>S", false },
      { "<leader>dps", false },
      { "<leader>e", false },
      { "<leader>fB", false },
      { "<leader>fE", false },
      { "<leader>fF", false },
      { "<leader>fR", false },
      { "<leader>fb", false },
      { "<leader>fc", false },
      { "<leader>fe", false },
      { "<leader>ff", false },
      { "<leader>fg", false },
      { "<leader>fp", false },
      { "<leader>fr", false },
      { "<leader>gD", false },
      { "<leader>gS", false },
      { "<leader>gs", false },
      { "<leader>n", false },
      { "<leader>s/", false },
      { "<leader>sB", false },
      { "<leader>sC", false },
      { "<leader>sD", false },
      { "<leader>sG", false },
      { "<leader>sH", false },
      { "<leader>sM", false },
      { "<leader>sR", false },
      { "<leader>sW", false, mode = { "n", "x" } },
      { "<leader>sa", false },
      { "<leader>sb", false },
      { "<leader>sc", false },
      { "<leader>si", false },
      { "<leader>sl", false },
      { "<leader>sp", false },
      { "<leader>su", false },
      { "<leader>sw", false, mode = { "n", "x" } },
      { "<leader>uC", false },
      { "<leader>un", false },
    },
  },
  {
    "folke/which-key.nvim",
    keys = {
      { "<c-w><space>", false },
      { "<leader>?", false },
    },
  },
}
