# GENERATED by scripts/cmd/generate-colors — DO NOT EDIT
# TOML source: colors/ghost-visor.toml

{
  metadata.name = "Ghost Visor";
  core = {
    background = "#202A42";
    darkest_bg = "#141B2D";
    panel_bg = "#324664";
    ui_shadow = "#242F48";
    active_line = "#314463";
    selection_bg = "#5199C2";
    selection_fg = "#141B2D";
  };
  foregrounds = {
    main = "#CDE9F5";
    bright = "#9FDBF7";
    dim = "#ADBAC9";
    subdued = "#949DB0";
    heading = "#88CBEA";
  };
  teals = {
    bright = "#58CAF8";
    mid_bright = "#92BFD9";
    standard = "#9ABED3";
    muted = "#3E6E8E";
    deep = "#2E6589";
    border = "#45799D";
    dark_accent = "#1C3A5E";
    sea_green = "#2F7D72";
  };
  blues_slates = {
    slate_mid = "#4A4953";
    punctuation_gray = "#B3B9C7";
    comment_gray = "#B1B9CA";
    git_blame_gray = "#B1B9CD";
    slate_dark = "#1F3265";
    ocean_blue = "#375F98";
    sky_slate = "#AFB8D9";
    cloud_slate = "#B8BCD8";
    deep_ocean = "#42547A";
  };
  purples = {
    lavender = "#D0D4F0";
    muted_purple = "#B4B6DA";
    bright_purple = "#CDACEC";
    dark_purple = "#4A3070";
    deep_glitch = "#6455C8";
    soft_magenta = "#C9B0D7";
    dark_rose = "#3A2A3E";
  };
  semantic = {
    success = "#62C9C2";
    warning = "#D0D4F0";
    error = "#CDACEC";
    info = "#58CAF8";
    comment = "#B1B9CA";
    git_blame = "#B1B9CD";
    string = "#9ABED3";
    keyword = "#B4B6DA";
    punctuation = "#B3B9C7";
    function = "#58CAF8";
    type = "#AFB8D9";
    variable = "#CDE9F5";
    number = "#9FDBF7";
    operator = "#92BFD9";
    constant = "#D0D4F0";
  };
  ansi = {
    black = "#141B2D";
    red = "#C67F9E";
    green = "#2FA5A0";
    yellow = "#C2B08D";
    blue = "#6393D7";
    magenta = "#D96DC0";
    cyan = "#58CAF8";
    white = "#CDE9F5";
    bright_black = "#5E5A63";
    bright_red = "#D38AA6";
    bright_green = "#52C4BC";
    bright_yellow = "#DFBE90";
    bright_blue = "#A8B2D6";
    bright_magenta = "#EBC1F8";
    bright_cyan = "#9FDBF7";
    bright_white = "#F8FCFD";
  };
  nvim = {
    bg = "#202A42";
    dark_shadow = "#242F48";
    gutter_bg = "#1A2235";
    selection = "#5199C2";
    border = "#45799D";
    comment = "#B1B9CA";
    git_blame = "#B1B9CD";
    punctuation = "#B3B9C7";
    string = "#9ABED3";
    keyword = "#B4B6DA";
    function = "#58CAF8";
    variable = "#CDE9F5";
    number = "#9FDBF7";
    type = "#AFB8D9";
    operator = "#92BFD9";
    header = "#88CBEA";
    diff_add_bg = "#1E3A44";
    diff_change_bg = "#2B2650";
    diff_delete_bg = "#302230";
    diff_add_inline_bg = "#2E5D6B";
    diff_change_inline_bg = "#4C3C78";
    diff_delete_inline_bg = "#5E3245";
  };
  zsh = {
    default = "#CDE9F5";
    command = "#58CAF8";
    path = "#88CBEA";
    string = "#9ABED3";
    option = "#AFB8D9";
    comment = "#B1B9CA";
    error = "#CEADE1";
  };
}
