# GENERATED by scripts/generate-colors.go — DO NOT EDIT
# TOML source: colors/ghost-visor.toml

{
  metadata.name = "Ghost Visor";
  core = {
    background = "#0A0C1A";
    darkest_bg = "#0E1127";
    panel_bg = "#102337";
    ui_shadow = "#191D2B";
    active_line = "#252A40";
    selection_bg = "#5199C2";
    selection_fg = "#0A0C1A";
  };
  foregrounds = {
    main = "#CDE9F5";
    bright = "#9FDBF7";
    dim = "#8296AC";
    heading = "#88CBEA";
  };
  teals = {
    bright = "#58CAF8";
    mid_bright = "#5199C2";
    standard = "#5F98B9";
    muted = "#3E6E8E";
    deep = "#2E6589";
    border = "#45799D";
    dark_accent = "#1C3A5E";
    sea_green = "#2F7D72";
  };
  blues_slates = {
    slate_mid = "#4A4953";
    punctuation_gray = "#8892A8";
    comment_gray = "#8692AD";
    git_blame_gray = "#8C97B5";
    slate_dark = "#1F3265";
    ocean_blue = "#375F98";
    sky_slate = "#A8B2D6";
    cloud_slate = "#B8BCD8";
    deep_ocean = "#30314B";
  };
  purples = {
    lavender = "#D0D4F0";
    muted_purple = "#8E92C8";
    bright_purple = "#B07AE0";
    dark_purple = "#4A3070";
    deep_glitch = "#6455C8";
    soft_magenta = "#9A6BB5";
    dark_rose = "#3A2A3E";
  };
  semantic = {
    success = "#52C4BC";
    warning = "#D0D4F0";
    error = "#B07AE0";
    info = "#58CAF8";
    comment = "#8692AD";
    git_blame = "#8C97B5";
    string = "#5F98B9";
    keyword = "#8E92C8";
    punctuation = "#8892A8";
    function = "#58CAF8";
    type = "#A8B2D6";
    variable = "#CDE9F5";
    number = "#9FDBF7";
    operator = "#5199C2";
    constant = "#D0D4F0";
  };
  ansi = {
    black = "#0E1127";
    red = "#C67F9E";
    green = "#2FA5A0";
    yellow = "#C9B078";
    blue = "#6393D7";
    magenta = "#D96DC0";
    cyan = "#58CAF8";
    white = "#CDE9F5";
    bright_black = "#5E5A63";
    bright_red = "#D38AA6";
    bright_green = "#52C4BC";
    bright_yellow = "#DCC98E";
    bright_blue = "#A8B2D6";
    bright_magenta = "#EBC1F8";
    bright_cyan = "#9FDBF7";
    bright_white = "#F8FCFD";
  };
  nvim = {
    bg = "#0A0C1A";
    dark_shadow = "#191D2B";
    gutter_bg = "#0D101F";
    selection = "#5199C2";
    border = "#45799D";
    comment = "#8692AD";
    git_blame = "#8C97B5";
    punctuation = "#8892A8";
    string = "#5F98B9";
    keyword = "#8E92C8";
    function = "#58CAF8";
    variable = "#CDE9F5";
    number = "#9FDBF7";
    type = "#A8B2D6";
    operator = "#5199C2";
    header = "#88CBEA";
    diff_add_bg = "#0D1F2A";
    diff_change_bg = "#191430";
    diff_delete_bg = "#1C1218";
    diff_add_inline_bg = "#1E4550";
    diff_change_inline_bg = "#3A2C5A";
    diff_delete_inline_bg = "#4A2333";
  };
  zsh = {
    default = "#CDE9F5";
    command = "#58CAF8";
    path = "#88CBEA";
    string = "#5F98B9";
    option = "#A8B2D6";
    comment = "#8692AD";
    error = "#B17DCF";
  };
}
