# GENERATED by scripts/cmd/generate-colors — DO NOT EDIT
# TOML source: colors/ghost-visor.toml

{
  metadata.name = "Ghost Visor";
  core = {
    background = "#1A2340";
    darkest_bg = "#0C1226";
    sunken_bg = "#141B34";
    panel_bg = "#332E56";
    ui_shadow = "#1F2745";
    active_line = "#2A3159";
    selection_bg = "#9385C8";
    selection_fg = "#0C1226";
  };
  foregrounds = {
    main = "#CDE9F5";
    bright = "#96D7F5";
    dim = "#ABA4C4";
    subdued = "#9E97B8";
    heading = "#B79AD0";
  };
  teals = {
    bright = "#58CAF8";
    mid_bright = "#92BFD9";
    standard = "#9ABED3";
    muted = "#3C5684";
    deep = "#33486F";
    border = "#4C4C74";
    dark_accent = "#253153";
    sea_green = "#2F7D72";
  };
  blues_slates = {
    slate_mid = "#453C5F";
    punctuation_gray = "#AEACC4";
    comment_gray = "#A5A2BC";
    git_blame_gray = "#A8A5C2";
    slate_dark = "#253153";
    ocean_blue = "#3C5684";
    sky_slate = "#AFB8D9";
    cloud_slate = "#BEB8D8";
    deep_ocean = "#33486F";
  };
  purples = {
    lavender = "#D0D4F0";
    muted_purple = "#B79AD0";
    bright_purple = "#CD73C9";
    dark_purple = "#453C5F";
    deep_glitch = "#885CCE";
    soft_magenta = "#C09BCE";
    dark_rose = "#3A2A42";
  };
  semantic = {
    success = "#76D6C4";
    warning = "#BEB8D8";
    error = "#E2839A";
    info = "#8AB8DE";
    hint = "#58CAF8";
    comment = "#A5A2BC";
    git_blame = "#A8A5C2";
    string = "#9ABED3";
    keyword = "#C69BF6";
    punctuation = "#AEACC4";
    function = "#58CAF8";
    type = "#AFB8D9";
    variable = "#CDE9F5";
    builtin_variable = "#88CBEA";
    number = "#96D7F5";
    operator = "#92BFD9";
    constant = "#D0D4F0";
  };
  git = {
    added = "#76D6C4";
    changed = "#CE7BD2";
    deleted = "#ABA4C4";
  };
  ui = {
    target_bg = "#D0D4F0";
    accent_fg = "#D0D4F0";
  };
  ansi = {
    black = "#0C1226";
    red = "#C97F9E";
    green = "#2FA5A0";
    yellow = "#CAB083";
    blue = "#7089D6";
    magenta = "#C86FBE";
    cyan = "#58CAF8";
    white = "#CDE9F5";
    bright_black = "#565273";
    bright_red = "#E2839A";
    bright_green = "#76D6C4";
    bright_yellow = "#DFBE90";
    bright_blue = "#AFB8D9";
    bright_magenta = "#E6BCF4";
    bright_cyan = "#96D7F5";
    bright_white = "#F8FCFD";
  };
  nvim = {
    bg = "#1A2340";
    dark_shadow = "#1F2745";
    selection = "#9385C8";
    border = "#4C4C74";
    comment = "#A5A2BC";
    git_blame = "#A8A5C2";
    punctuation = "#AEACC4";
    string = "#9ABED3";
    keyword = "#C69BF6";
    function = "#58CAF8";
    variable = "#CDE9F5";
    number = "#96D7F5";
    type = "#AFB8D9";
    operator = "#92BFD9";
    header = "#B79AD0";
    diff_add_bg = "#1A3D48";
    diff_change_bg = "#332A5E";
    diff_delete_bg = "#421F32";
    diff_add_inline_bg = "#2E6472";
    diff_change_inline_bg = "#52458F";
    diff_delete_inline_bg = "#71364A";
  };
  zsh = {
    default = "#CDE9F5";
    command = "#58CAF8";
    path = "#B79AD0";
    string = "#9ABED3";
    option = "#AFB8D9";
    comment = "#A5A2BC";
  };
}
